### 1.Load To The DataSet.

In [12]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (6.1.3)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
!pip install pandas

!pip install pyaml

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pyaml in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (26.7.0)
Requirement already satisfied: PyYAML in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pyaml) (6.0.3)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import pandas as pd
import json
import yaml

In [15]:
# 1. SKU TABLE - XML
sku_df = pd.read_xml("SKU_TABLE_1.xml")


# 2. PL TABLE - JSON Lines
pl_df = pd.read_json("PL_TABLE_2.json", lines=True)


# 3. SELLER MAPPING TABLE - Excel
seller_mapping_df = pd.read_excel("SELLER_MAPPING_TABLE_3.xlsx")


# 4. PRICE LIST TABLE - YAML
with open("PRICE_LIST_TABLE_4.yaml", "r") as file:
    price_data = yaml.safe_load(file)

price_df = pd.DataFrame(price_data)


# 5. CATEGORY MAPPING TABLE - JSON Lines
category_df = pd.read_json(
    "CATEGORY_MAPPING_TABLE_5.json",
    lines=True
)


# 6. PROMOTION TABLE - Excel
promotion_df = pd.read_excel("PROMOTION_TABLE_6.xlsx")

In [16]:
sku_df

              PN      Sku
0        Pib01a1  0X749QB
1        Pib01a2  75X62BB
2        Pib01a3   DF627B
3        Pib01a4   4ZB96A
4        Pib01a5  0R0N0QB
...          ...      ...
1593  Pib01a1594  4KB93BB
1594  Pib01a1595   X2231B
1595  Pib01a1596   B3P21A
1596  Pib01a1597  78X20QB
1597  Pib01a1598   CF364A

[1598 rows x 2 columns]

In [17]:
pl_df

                     PL      sku
0      DELL0X_PC_Laptop  0X749QB
1     DELL75_PC_Monitor  75X62BB
2        DELLDF_SUP_TON   DF627B
3            HP4Z_PH_LJ   4ZB96A
4      DELL0R_PC_Laptop  0R0N0QB
...                 ...      ...
1593     DELL4K_SUP_INK  4KB93BB
1594     DELLX2_SUP_TON   X2231B
1595       HPB3_SUP_INK   B3P21A
1596  DELL78_PC_Desktop  78X20QB
1597       HPCF_SUP_TON   CF364A

[1598 rows x 2 columns]

In [18]:
seller_mapping_df

                  Ssellers_name           homologated_sellers
0                Cocoblu Retail           BJ's Wholesale Club
1      RK World Infocom Pvt Ltd                American Eagle
2    Appario Retail Private Ltd                      Tapestry
3              RetailEZ Pvt Ltd           Wakefern / ShopRite
4                 ETrade Online          Harbor Freight Tools
..                          ...                           ...
898            Hydroshell India  Barnes and Noble Booksellers
899                 KT FASHIONS           J.C. Penney Company
900               Shoplite 0000                      Tapestry
901                 Bestbuybook        Sprouts Farmers Market
902                  Seetabooks                  Advance Auto

[903 rows x 2 columns]

In [19]:
price_df

         MAP                 PL      sku
0     106684   DELL0X_PC_Laptop  0X749QB
1      35611  DELL75_PC_Monitor  75X62BB
2      29914     DELLDF_SUP_TON   DF627B
3      39258         HP4Z_PH_LJ   4ZB96A
4     139670   DELL0R_PC_Laptop  0R0N0QB
...      ...                ...      ...
1593    3565     DELL4K_SUP_INK  4KB93BB
1594    6716     DELLX2_SUP_TON   X2231B
1595    6868       HPB3_SUP_INK   B3P21A
1596   47937  DELL78_PC_Desktop  78X20QB
1597   28243       HPCF_SUP_TON   CF364A

[1598 rows x 3 columns]

In [20]:
category_df

          sku                 PL
0     0X749QB   DELL0X_PC_Laptop
1     75X62BB  DELL75_PC_Monitor
2      DF627B     DELLDF_SUP_TON
3      4ZB96A         HP4Z_PH_LJ
4     0R0N0QB   DELL0R_PC_Laptop
...       ...                ...
1593  4KB93BB     DELL4K_SUP_INK
1594   X2231B     DELLX2_SUP_TON
1595   B3P21A       HPB3_SUP_INK
1596  78X20QB  DELL78_PC_Desktop
1597   CF364A       HPCF_SUP_TON

[1598 rows x 2 columns]

In [21]:
promotion_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,Promotion Table,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Offer table,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
109,NaN,7KW56A,NaN,NaN,NaN,NaN,NaN
110,NaN,X2214B,NaN,NaN,NaN,NaN,NaN
111,NaN,8F8Z3PA,NaN,NaN,NaN,NaN,NaN
112,NaN,77S54PA,NaN,NaN,NaN,NaN,NaN
113,NaN,B3P21A,NaN,NaN,NaN,NaN,NaN

In [22]:
# Clean column names
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    return df

sku_df = clean_columns(sku_df)
pl_df = clean_columns(pl_df)
seller_mapping_df = clean_columns(seller_mapping_df)
price_df = clean_columns(price_df)
category_df = clean_columns(category_df)

In [23]:
for df in [sku_df, pl_df, seller_mapping_df, price_df, category_df]:

    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].astype("string").str.strip()

In [24]:
parts = category_df["pl"].str.split("_", n=2, expand=True)

category_df["category"] = parts[1]
category_df["sub_category"] = parts[2]

In [25]:
category_df.head(10)

       sku                 pl category sub_category
0  0X749QB   DELL0X_PC_Laptop       PC       Laptop
1  75X62BB  DELL75_PC_Monitor       PC      Monitor
2   DF627B     DELLDF_SUP_TON      SUP          TON
3   4ZB96A         HP4Z_PH_LJ       PH           LJ
4  0R0N0QB   DELL0R_PC_Laptop       PC       Laptop
5   7LE37B       DELL7L_PH_IJ       PH           IJ
6  89Z55QB  DELL89_PC_Desktop       PC      Desktop
7  8C4R9PA     HP8C_PC_Laptop       PC       Laptop
8   G0L15B     DELLG0_SUP_INK      SUP          INK
9   DF853B     DELLDF_SUP_TON      SUP          TON

In [26]:
category_map = category_df[
    ["sku", "category", "sub_category"]
].drop_duplicates("sku")

In [27]:
pl_df = pl_df.merge(
    category_map,
    on="sku",
    how="left"
)

In [28]:
pl_df.head(10)

                  pl      sku category sub_category
0   DELL0X_PC_Laptop  0X749QB       PC       Laptop
1  DELL75_PC_Monitor  75X62BB       PC      Monitor
2     DELLDF_SUP_TON   DF627B      SUP          TON
3         HP4Z_PH_LJ   4ZB96A       PH           LJ
4   DELL0R_PC_Laptop  0R0N0QB       PC       Laptop
5       DELL7L_PH_IJ   7LE37B       PH           IJ
6  DELL89_PC_Desktop  89Z55QB       PC      Desktop
7     HP8C_PC_Laptop  8C4R9PA       PC       Laptop
8     DELLG0_SUP_INK   G0L15B      SUP          INK
9     DELLDF_SUP_TON   DF853B      SUP          TON

In [29]:
category_df["sub_category"].value_counts()

sub_category
INK        426
Laptop     416
TON        326
Desktop    164
IJ          84
LJ          74
Monitor     60
UNK         28
SJ          20
Name: count, dtype: Int64

### 2.normalize to the catogry names.

In [30]:
sub_category_map = {
    "TON": "Toner",
    "LJ": "Laserjet",
    "IJ": "Inkjet",
    "INK": "Ink",
    "SJ": "SJ",
    "UNK": "UNK",
    "Laptop": "Laptop",
    "Monitor": "Monitor",
    "Desktop": "Desktop"
}

pl_df["lpp_sub_category"] = pl_df["sub_category"].map(sub_category_map)

pl_df[["pl", "sub_category", "lpp_sub_category"]].head(10)

                  pl sub_category lpp_sub_category
0   DELL0X_PC_Laptop       Laptop           Laptop
1  DELL75_PC_Monitor      Monitor          Monitor
2     DELLDF_SUP_TON          TON            Toner
3         HP4Z_PH_LJ           LJ         Laserjet
4   DELL0R_PC_Laptop       Laptop           Laptop
5       DELL7L_PH_IJ           IJ           Inkjet
6  DELL89_PC_Desktop      Desktop          Desktop
7     HP8C_PC_Laptop       Laptop           Laptop
8     DELLG0_SUP_INK          INK              Ink
9     DELLDF_SUP_TON          TON            Toner

### 3.identify the brand

In [31]:
pl_df["brand"] = pl_df["pl"].str.extract(r"^(DELL|HP)", expand=False)

pl_df[["pl", "brand"]].head(10)

                  pl brand
0   DELL0X_PC_Laptop  DELL
1  DELL75_PC_Monitor  DELL
2     DELLDF_SUP_TON  DELL
3         HP4Z_PH_LJ    HP
4   DELL0R_PC_Laptop  DELL
5       DELL7L_PH_IJ  DELL
6  DELL89_PC_Desktop  DELL
7     HP8C_PC_Laptop    HP
8     DELLG0_SUP_INK  DELL
9     DELLDF_SUP_TON  DELL

### 4.create LPP Perccentage mapping.

In [32]:
lpp_rates = {
    ("HP", "Laptop"): 0.034,
    ("DELL", "Laptop"): 0.078,

    ("HP", "Monitor"): 0.012,
    ("DELL", "Monitor"): 0.056,

    ("HP", "Toner"): 0.091,
    ("DELL", "Toner"): 0.023,

    ("HP", "Laserjet"): 0.065,
    ("DELL", "Laserjet"): 0.035,

    ("HP", "Inkjet"): 0.012,
    ("DELL", "Inkjet"): 0.056,

    ("HP", "Desktop"): 0.091,
    ("DELL", "Desktop"): 0.023,

    ("HP", "Ink"): 0.065,
    ("DELL", "Ink"): 0.035
}

In [33]:
pl_df["lpp_percentage"] = [
    lpp_rates.get((brand, subcat))
    for brand, subcat in zip(
        pl_df["brand"],
        pl_df["lpp_sub_category"]
    )
]

In [34]:
pl_df[
    ["pl", "brand", "sub_category", "lpp_sub_category", "lpp_percentage"]
].head(20)

                   pl brand sub_category lpp_sub_category  lpp_percentage
0    DELL0X_PC_Laptop  DELL       Laptop           Laptop           0.078
1   DELL75_PC_Monitor  DELL      Monitor          Monitor           0.056
2      DELLDF_SUP_TON  DELL          TON            Toner           0.023
3          HP4Z_PH_LJ    HP           LJ         Laserjet           0.065
4    DELL0R_PC_Laptop  DELL       Laptop           Laptop           0.078
5        DELL7L_PH_IJ  DELL           IJ           Inkjet           0.056
6   DELL89_PC_Desktop  DELL      Desktop          Desktop           0.023
7      HP8C_PC_Laptop    HP       Laptop           Laptop           0.034
8      DELLG0_SUP_INK  DELL          INK              Ink           0.035
9      DELLDF_SUP_TON  DELL          TON            Toner           0.023
10       HPCN_SUP_INK    HP          INK              Ink           0.065
11       HPC2_SUP_INK    HP          INK              Ink           0.065
12       HPC2_SUP_INK    HP          INK              Ink           0.065
13     DELL4F_SUP_INK  DELL          INK              Ink           0.035
14     DELLDG_SUP_TON  DELL          TON            Toner           0.023
15     HP8F_PC_Laptop    HP       Laptop           Laptop           0.034
16       HP4K_SUP_INK    HP          INK              Ink           0.065
17     HP8F_PC_Laptop    HP       Laptop           Laptop           0.034
18       HPL0_SUP_UNK    HP          UNK              UNK             NaN
19         HPT8_PH_IJ    HP           IJ           Inkjet           0.012

### find unk rows

In [35]:
pl_df[pl_df["sub_category"] == "UNK"][
    ["pl", "sku", "brand", "sub_category", "lpp_percentage"]
]

                  pl      sku brand sub_category  lpp_percentage
18      HPL0_SUP_UNK  L0R91AA    HP          UNK             NaN
94    DELL7A_SUP_UNK  7AE72BB  DELL          UNK             NaN
235   DELLK4_SUP_UNK   K4N82B  DELL          UNK             NaN
289     HPJ3_SUP_UNK   J3M68A    HP          UNK             NaN
342   DELLM1_SUP_UNK  M1S05BB  DELL          UNK             NaN
372     HPL0_SUP_UNK  L0S06AA    HP          UNK             NaN
636   DELLM1_SUP_UNK  M1T17BB  DELL          UNK             NaN
640     HPL0_SUP_UNK  L0R88AA    HP          UNK             NaN
786   DELLK4_SUP_UNK   K4N79B  DELL          UNK             NaN
867   DELLM1_SUP_UNK  M1S02BB  DELL          UNK             NaN
950     HP6Z_SUP_UNK  6ZD21AA    HP          UNK             NaN
970   DELLM1_SUP_UNK  M1S08BB  DELL          UNK             NaN
976   DELL7A_SUP_UNK  7AE32BB  DELL          UNK             NaN
1013  DELLK4_SUP_UNK   K4N81B  DELL          UNK             NaN
1017    HPL0_SUP_UNK  L0S00AA    HP          UNK             NaN
1044    HPJ3_SUP_UNK   J3M70A    HP          UNK             NaN
1068  DELLK4_SUP_UNK   K4N70B  DELL          UNK             NaN
1107    HPJ3_SUP_UNK   J3M69A    HP          UNK             NaN
1173    HPJ3_SUP_UNK   J3M71A    HP          UNK             NaN
1191    HPL0_SUP_UNK  L0S03AA    HP          UNK             NaN
1193  DELLM1_SUP_UNK  M1T14BB  DELL          UNK             NaN
1226  DELLM1_SUP_UNK  M1T11BB  DELL          UNK             NaN
1291    HP6Z_SUP_UNK  6ZD61AA    HP          UNK             NaN
1337    HPL0_SUP_UNK  L0S09AA    HP          UNK             NaN
1350    HPL0_SUP_UNK  L0R97AA    HP          UNK             NaN
1401  DELLM1_SUP_UNK  M1S99BB  DELL          UNK             NaN
1413  DELLM1_SUP_UNK  M1T10BB  DELL          UNK             NaN
1454    HPL0_SUP_UNK  L0R94AA    HP          UNK             NaN

In [36]:
print("UNK count:", (pl_df["sub_category"] == "UNK").sum())

print(
    pl_df.loc[
        pl_df["sub_category"] == "UNK",
        "pl"
    ].value_counts()
)

UNK count: 28
pl
HPL0_SUP_UNK      8
DELLM1_SUP_UNK    8
HPJ3_SUP_UNK      4
DELLK4_SUP_UNK    4
DELL7A_SUP_UNK    2
HP6Z_SUP_UNK      2
Name: count, dtype: Int64

In [37]:
pl_df.loc[
    pl_df["sub_category"] == "UNK",
    "lpp_percentage"
].isna().all()

np.True_

In [38]:
price_df = price_df.merge(
    pl_df[
        ["sku", "brand", "category",
         "sub_category", "lpp_sub_category",
         "lpp_percentage"]
    ],
    on="sku",
    how="left"
)

In [39]:
price_df["lpp"] = (
    price_df["map"] *
    (1 - price_df["lpp_percentage"])
)

In [40]:
price_df[
    ["MAP", "PL", "sku", "brand",
     "sub_category", "lpp_percentage", "LPP"]
].head(20)

KeyError: "['MAP', 'PL', 'LPP'] not in index"

In [41]:
price_df.columns.tolist()

['map',
 'pl',
 'sku',
 'brand',
 'category',
 'sub_category',
 'lpp_sub_category',
 'lpp_percentage',
 'lpp']

In [42]:
price_df[
    ["map", "pl", "sku", "brand",
     "sub_category", "lpp_percentage", "lpp"]
].head(20)

,map,pl,sku,brand,sub_category,lpp_percentage,lpp
0,106684,DELL0X_PC_Laptop,0X749QB,DELL,Laptop,0.078,98362.648
1,35611,DELL75_PC_Monitor,75X62BB,DELL,Monitor,0.056,33616.784
2,29914,DELLDF_SUP_TON,DF627B,DELL,TON,0.023,29225.978
3,39258,HP4Z_PH_LJ,4ZB96A,HP,LJ,0.065,36706.230
4,139670,DELL0R_PC_Laptop,0R0N0QB,DELL,Laptop,0.078,128775.740
5,993854,DELL7L_PH_IJ,7LE37B,DELL,IJ,0.056,938198.176
6,49687,DELL89_PC_Desktop,89Z55QB,DELL,Desktop,0.023,48544.199
7,102079,HP8C_PC_Laptop,8C4R9PA,HP,Laptop,0.034,98608.314
8,9900,DELLG0_SUP_INK,G0L15B,DELL,INK,0.035,9553.500
9,28788,DELLDF_SUP_TON,DF853B,DELL,TON,0.023,28125.876
10,5296,HPCN_SUP_INK,CN045AA,HP,INK,0.065,4951.760
11,3547,HPC2_SUP_INK,C2P23AA,HP,INK,0.065,3316.445
12,1419,HPC2_SUP_INK,C2P21AA,HP,INK,0.065,1326.765
13,1749,DELL4F_SUP_INK,4FE79B,DELL,INK,0.035,1687.785
14,25865,DELLDG_SUP_TON,DG460B,DELL,TON,0.023,25270.105
15,120699,HP8F_PC_Laptop,8F6C9PA,HP,Laptop,0.034,116595.234
16,1995,HP4K_SUP_INK,4K0V9PA,HP,INK,0.065,1865.325
17,184299,HP8F_PC_Laptop,8F8Z8PA,HP,Laptop,0.034,178032.834
18,7788,HPL0_SUP_UNK,L0R91AA,HP,UNK,NaN,NaN
19,258399,HPT8_PH_IJ,T8W15A,HP,IJ,0.012,255298.212

In [43]:
price_df[["map", "lpp_percentage", "lpp"]].head(10)

      map  lpp_percentage         lpp
0  106684           0.078   98362.648
1   35611           0.056   33616.784
2   29914           0.023   29225.978
3   39258           0.065   36706.230
4  139670           0.078  128775.740
5  993854           0.056  938198.176
6   49687           0.023   48544.199
7  102079           0.034   98608.314
8    9900           0.035    9553.500
9   28788           0.023   28125.876

In [44]:
print("Total rows:", len(price_df))
print("Missing LPP:", price_df["lpp"].isna().sum())

Total rows: 1606
Missing LPP: 48

In [45]:
price_df[
    price_df["lpp"].isna()
][
    ["map", "pl", "sku", "brand",
     "sub_category", "lpp_percentage", "lpp"]
]

         map              pl      sku brand sub_category  lpp_percentage  lpp
18      7788    HPL0_SUP_UNK  L0R91AA    HP          UNK             NaN  NaN
94       528  DELL7A_SUP_UNK  7AE72BB  DELL          UNK             NaN  NaN
115    90473    DELL31_PH_SJ   31H19B  DELL           SJ             NaN  NaN
207    25856    DELL7G_PH_SJ   7GX17B  DELL           SJ             NaN  NaN
236     7897  DELLK4_SUP_UNK   K4N82B  DELL          UNK             NaN  NaN
290    10249    HPJ3_SUP_UNK   J3M68A    HP          UNK             NaN  NaN
343     8243  DELLM1_SUP_UNK  M1S05BB  DELL          UNK             NaN  NaN
371    54367    DELL7G_PH_SJ   7GX10B  DELL           SJ             NaN  NaN
373    11434    HPL0_SUP_UNK  L0S06AA    HP          UNK             NaN  NaN
425    45395    DELL31_PH_SJ   31H17B  DELL           SJ             NaN  NaN
455    30688      HP6F_PH_SJ   6FW07A    HP           SJ             NaN  NaN
519    48741      HP6F_PH_SJ   6FW09A    HP           SJ             NaN  NaN
541    54502      HP20_PH_SJ   20G07A    HP           SJ             NaN  NaN
564    67415      HP6F_PH_SJ   6FW10A    HP           SJ             NaN  NaN
619    45789      HP6F_PH_SJ   6FW08A    HP           SJ             NaN  NaN
638    12510  DELLM1_SUP_UNK  M1T17BB  DELL          UNK             NaN  NaN
642     7879    HPL0_SUP_UNK  L0R88AA    HP          UNK             NaN  NaN
686    65166    DELL7G_PH_SJ   7GX21B  DELL           SJ             NaN  NaN
687    23550      HP20_PH_SJ   20G05A    HP           SJ             NaN  NaN
743    45959      HP20_PH_SJ   20G06A    HP           SJ             NaN  NaN
788    11640  DELLK4_SUP_UNK   K4N79B  DELL          UNK             NaN  NaN
801    44338    DELL7G_PH_SJ   7GX19B  DELL           SJ             NaN  NaN
828    83736      HP20_PH_SJ   20G08A    HP           SJ             NaN  NaN
869     8690  DELLM1_SUP_UNK  M1S02BB  DELL          UNK             NaN  NaN
953      529    HP6Z_SUP_UNK  6ZD21AA    HP          UNK             NaN  NaN
973     8334  DELLM1_SUP_UNK  M1S08BB  DELL          UNK             NaN  NaN
979      554  DELL7A_SUP_UNK  7AE32BB  DELL          UNK             NaN  NaN
1009   25617      HP6F_PH_SJ   6FW06A    HP           SJ             NaN  NaN
1016   10799  DELLK4_SUP_UNK   K4N81B  DELL          UNK             NaN  NaN
1020   12083    HPL0_SUP_UNK  L0S00AA    HP          UNK             NaN  NaN
1048   11428    HPJ3_SUP_UNK   J3M70A    HP          UNK             NaN  NaN
1073   11493  DELLK4_SUP_UNK   K4N70B  DELL          UNK             NaN  NaN
1112   11310    HPJ3_SUP_UNK   J3M69A    HP          UNK             NaN  NaN
1121  240565    DELLM3_PH_SJ   M3874B  DELL           SJ             NaN  NaN
1178    7548    HPJ3_SUP_UNK   J3M71A    HP          UNK             NaN  NaN
1196   11434    HPL0_SUP_UNK  L0S03AA    HP          UNK             NaN  NaN
1198   12427  DELLM1_SUP_UNK  M1T14BB  DELL          UNK             NaN  NaN
1231   12390  DELLM1_SUP_UNK  M1T11BB  DELL          UNK             NaN  NaN
1288  223978      HPL2_PH_SJ   L2763A    HP           SJ             NaN  NaN
1297     509    HP6Z_SUP_UNK  6ZD61AA    HP          UNK             NaN  NaN
1344   11752    HPL0_SUP_UNK  L0S09AA    HP          UNK             NaN  NaN
1357    7345    HPL0_SUP_UNK  L0R97AA    HP          UNK             NaN  NaN
1409    8361  DELLM1_SUP_UNK  M1S99BB  DELL          UNK             NaN  NaN
1421   12485  DELLM1_SUP_UNK  M1T10BB  DELL          UNK             NaN  NaN
1462    8060    HPL0_SUP_UNK  L0R94AA    HP          UNK             NaN  NaN
1522   34575    DELL7G_PH_SJ   7GX18B  DELL           SJ             NaN  NaN
1542   24266    DELL31_PH_SJ   31H16B  DELL           SJ             NaN  NaN
1550   63318    DELL31_PH_SJ   31H18B  DELL           SJ             NaN  NaN

In [46]:
price_df.loc[
    price_df["lpp_percentage"].isna(),
    "sub_category"
].value_counts()

sub_category
UNK    28
SJ     20
Name: count, dtype: Int64

In [47]:
lpp_missing = price_df[
    price_df["lpp_percentage"].isna()
][
    ["map", "pl", "sku", "brand", "category",
     "sub_category", "lpp_percentage", "lpp"]
]

lpp_missing

,map,pl,sku,brand,category,sub_category,lpp_percentage,lpp
18,7788,HPL0_SUP_UNK,L0R91AA,HP,SUP,UNK,NaN,NaN
94,528,DELL7A_SUP_UNK,7AE72BB,DELL,SUP,UNK,NaN,NaN
115,90473,DELL31_PH_SJ,31H19B,DELL,PH,SJ,NaN,NaN
207,25856,DELL7G_PH_SJ,7GX17B,DELL,PH,SJ,NaN,NaN
236,7897,DELLK4_SUP_UNK,K4N82B,DELL,SUP,UNK,NaN,NaN
290,10249,HPJ3_SUP_UNK,J3M68A,HP,SUP,UNK,NaN,NaN
343,8243,DELLM1_SUP_UNK,M1S05BB,DELL,SUP,UNK,NaN,NaN
371,54367,DELL7G_PH_SJ,7GX10B,DELL,PH,SJ,NaN,NaN
373,11434,HPL0_SUP_UNK,L0S06AA,HP,SUP,UNK,NaN,NaN
425,45395,DELL31_PH_SJ,31H17B,DELL,PH,SJ,NaN,NaN
455,30688,HP6F_PH_SJ,6FW07A,HP,PH,SJ,NaN,NaN
519,48741,HP6F_PH_SJ,6FW09A,HP,PH,SJ,NaN,NaN
541,54502,HP20_PH_SJ,20G07A,HP,PH,SJ,NaN,NaN
564,67415,HP6F_PH_SJ,6FW10A,HP,PH,SJ,NaN,NaN
619,45789,HP6F_PH_SJ,6FW08A,HP,PH,SJ,NaN,NaN
638,12510,DELLM1_SUP_UNK,M1T17BB,DELL,SUP,UNK,NaN,NaN
642,7879,HPL0_SUP_UNK,L0R88AA,HP,SUP,UNK,NaN,NaN
686,65166,DELL7G_PH_SJ,7GX21B,DELL,PH,SJ,NaN,NaN
687,23550,HP20_PH_SJ,20G05A,HP,PH,SJ,NaN,NaN
743,45959,HP20_PH_SJ,20G06A,HP,PH,SJ,NaN,NaN
788,11640,DELLK4_SUP_UNK,K4N79B,DELL,SUP,UNK,NaN,NaN
801,44338,DELL7G_PH_SJ,7GX19B,DELL,PH,SJ,NaN,NaN
828,83736,HP20_PH_SJ,20G08A,HP,PH,SJ,NaN,NaN
869,8690,DELLM1_SUP_UNK,M1S02BB,DELL,SUP,UNK,NaN,NaN
953,529,HP6Z_SUP_UNK,6ZD21AA,HP,SUP,UNK,NaN,NaN
973,8334,DELLM1_SUP_UNK,M1S08BB,DELL,SUP,UNK,NaN,NaN
979,554,DELL7A_SUP_UNK,7AE32BB,DELL,SUP,UNK,NaN,NaN
1009,25617,HP6F_PH_SJ,6FW06A,HP,PH,SJ,NaN,NaN
1016,10799,DELLK4_SUP_UNK,K4N81B,DELL,SUP,UNK,NaN,NaN
1020,12083,HPL0_SUP_UNK,L0S00AA,HP,SUP,UNK,NaN,NaN
1048,11428,HPJ3_SUP_UNK,J3M70A,HP,SUP,UNK,NaN,NaN
1073,11493,DELLK4_SUP_UNK,K4N70B,DELL,SUP,UNK,NaN,NaN
1112,11310,HPJ3_SUP_UNK,J3M69A,HP,SUP,UNK,NaN,NaN
1121,240565,DELLM3_PH_SJ,M3874B,DELL,PH,SJ,NaN,NaN
1178,7548,HPJ3_SUP_UNK,J3M71A,HP,SUP,UNK,NaN,NaN
1196,11434,HPL0_SUP_UNK,L0S03AA,HP,SUP,UNK,NaN,NaN
1198,12427,DELLM1_SUP_UNK,M1T14BB,DELL,SUP,UNK,NaN,NaN
1231,12390,DELLM1_SUP_UNK,M1T11BB,DELL,SUP,UNK,NaN,NaN
1288,223978,HPL2_PH_SJ,L2763A,HP,PH,SJ,NaN,NaN
1297,509,HP6Z_SUP_UNK,6ZD61AA,HP,SUP,UNK,NaN,NaN
1344,11752,HPL0_SUP_UNK,L0S09AA,HP,SUP,UNK,NaN,NaN
1357,7345,HPL0_SUP_UNK,L0R97AA,HP,SUP,UNK,NaN,NaN
1409,8361,DELLM1_SUP_UNK,M1S99BB,DELL,SUP,UNK,NaN,NaN
1421,12485,DELLM1_SUP_UNK,M1T10BB,DELL,SUP,UNK,NaN,NaN
1462,8060,HPL0_SUP_UNK,L0R94AA,HP,SUP,UNK,NaN,NaN
1522,34575,DELL7G_PH_SJ,7GX18B,DELL,PH,SJ,NaN,NaN
1542,24266,DELL31_PH_SJ,31H16B,DELL,PH,SJ,NaN,NaN
1550,63318,DELL31_PH_SJ,31H18B,DELL,PH,SJ,NaN,NaN

In [48]:
print("Total rows:", len(price_df))
print("LPP calculated:", price_df["lpp"].notna().sum())
print("LPP missing:", price_df["lpp"].isna().sum())

Total rows: 1606
LPP calculated: 1558
LPP missing: 48

In [49]:
price_df.to_csv("PRICE_LIST_CLEANED.csv", index=False)

In [50]:
seller_mapping_df.columns

Index(['ssellers_name', 'homologated_sellers'], dtype='object')

In [51]:
seller_mapping_df = seller_mapping_df.rename(columns={
    "ssellers_name":"Seller_Name",
    "homologated_sellers":"Homologated_Name"
})

In [52]:
seller_mapping_df.head()

                  Seller_Name      Homologated_Name
0              Cocoblu Retail   BJ's Wholesale Club
1    RK World Infocom Pvt Ltd        American Eagle
2  Appario Retail Private Ltd              Tapestry
3            RetailEZ Pvt Ltd   Wakefern / ShopRite
4               ETrade Online  Harbor Freight Tools

In [53]:
seller_mapping_df["Seller_Name"] = (
    seller_mapping_df["Seller_Name"]
    .astype("string")
    .str.strip()
)

seller_mapping_df["Homologated_Name"] = (
    seller_mapping_df["Homologated_Name"]
    .astype("string")
    .str.strip()
)

In [54]:
print("Rows:", len(seller_mapping_df))
print("Missing Seller_Name:", seller_mapping_df["Seller_Name"].isna().sum())
print("Missing Homologated_Name:", seller_mapping_df["Homologated_Name"].isna().sum())

Rows: 903
Missing Seller_Name: 0
Missing Homologated_Name: 0

In [55]:
seller_mapping_df[
    seller_mapping_df["Seller_Name"].duplicated(keep=False)
].sort_values("Seller_Name")

    Seller_Name        Homologated_Name
100      Seller  Sprouts Farmers Market
301      Seller                7-Eleven
602      Seller      Tractor Supply Co.

In [56]:
seller_mapping_df.groupby("Seller_Name")["Homologated_Name"].nunique().sort_values(ascending=False).head(10)

Seller_Name
Seller                                 3
Zelixon Lifestyle                      1
ARIKA ENTERPRISES LLP                  1
kingster.                              1
k3stores®                              1
40km                                   1
AARSH LIFESTYLE                        1
ABOUT SPACE                            1
ACEFOUR ACCESSORIES PRIVATE LIMITED    1
ADDMAX                                 1
Name: Homologated_Name, dtype: int64

In [57]:
seller_mapping_df[
    seller_mapping_df["Seller_Name"] == "Seller"
]

    Seller_Name        Homologated_Name
100      Seller  Sprouts Farmers Market
301      Seller                7-Eleven
602      Seller      Tractor Supply Co.

In [58]:
seller_mapping_df[
    seller_mapping_df["Seller_Name"] == "Seller"
].to_dict("records")

[{'Seller_Name': 'Seller', 'Homologated_Name': 'Sprouts Farmers Market'},
 {'Seller_Name': 'Seller', 'Homologated_Name': '7-Eleven'},
 {'Seller_Name': 'Seller', 'Homologated_Name': 'Tractor Supply Co.'}]

In [59]:
seller_mapping_df.duplicated().sum()

np.int64(0)

In [60]:
seller_mapping_df.groupby("Seller_Name")["Homologated_Name"].nunique().sort_values(
    ascending=False
).head(20)

Seller_Name
Seller                                 3
Zelixon Lifestyle                      1
ARIKA ENTERPRISES LLP                  1
kingster.                              1
k3stores®                              1
40km                                   1
AARSH LIFESTYLE                        1
ABOUT SPACE                            1
ACEFOUR ACCESSORIES PRIVATE LIMITED    1
ADDMAX                                 1
AEROTECHENTERPRISE                     1
AHshoppers                             1
AK Credible                            1
ALBERTO INFOTECH                       1
ALOUD CREATIONS®                       1
ALROZA                                 1
AMIRAT CLOTHING                        1
ANAND BOOKS AGRA                       1
ANII ENTERPRISE                        1
ARIES LIFESTYLE                        1
Name: Homologated_Name, dtype: int64

In [61]:
seller_mapping_df[
    seller_mapping_df.groupby("Seller_Name")["Homologated_Name"].transform("nunique") > 1
].sort_values("Seller_Name")

    Seller_Name        Homologated_Name
100      Seller  Sprouts Farmers Market
301      Seller                7-Eleven
602      Seller      Tractor Supply Co.

In [62]:
# Check unique values
print("Total rows:", len(seller_mapping_df))
print("Unique Seller_Name:", seller_mapping_df["Seller_Name"].nunique())
print("Unique Homologated_Name:", seller_mapping_df["Homologated_Name"].nunique())

# Check missing values
print("Missing Seller_Name:", seller_mapping_df["Seller_Name"].isna().sum())
print("Missing Homologated_Name:", seller_mapping_df["Homologated_Name"].isna().sum())

Total rows: 903
Unique Seller_Name: 901
Unique Homologated_Name: 100
Missing Seller_Name: 0
Missing Homologated_Name: 0

In [63]:
seller_mapping_df.to_csv(
    "SELLER_MAPPING_TABLE_CLEANED.csv",
    index=False
)

In [64]:
seller_mapping_df.head(10)

                            Seller_Name          Homologated_Name
0                        Cocoblu Retail       BJ's Wholesale Club
1              RK World Infocom Pvt Ltd            American Eagle
2            Appario Retail Private Ltd                  Tapestry
3                      RetailEZ Pvt Ltd       Wakefern / ShopRite
4                         ETrade Online      Harbor Freight Tools
5                      Clicktech Retail              Weis Markets
6                             Jensi2304         H.E. Butt Grocery
7  DAWNTECH ELECTRONICS PRIVATE LIMITED  Alimentation Couche-Tard
8                          Shadow Etail                      Aldi
9                                DeckUp                   Wayfair

### categrory data cleaning.

In [65]:
category_df

          sku                 pl category sub_category
0     0X749QB   DELL0X_PC_Laptop       PC       Laptop
1     75X62BB  DELL75_PC_Monitor       PC      Monitor
2      DF627B     DELLDF_SUP_TON      SUP          TON
3      4ZB96A         HP4Z_PH_LJ       PH           LJ
4     0R0N0QB   DELL0R_PC_Laptop       PC       Laptop
...       ...                ...      ...          ...
1593  4KB93BB     DELL4K_SUP_INK      SUP          INK
1594   X2231B     DELLX2_SUP_TON      SUP          TON
1595   B3P21A       HPB3_SUP_INK      SUP          INK
1596  78X20QB  DELL78_PC_Desktop       PC      Desktop
1597   CF364A       HPCF_SUP_TON      SUP          TON

[1598 rows x 4 columns]

In [66]:
category_df.columns.tolist()

['sku', 'pl', 'category', 'sub_category']

In [67]:
category_df.head(10)

       sku                 pl category sub_category
0  0X749QB   DELL0X_PC_Laptop       PC       Laptop
1  75X62BB  DELL75_PC_Monitor       PC      Monitor
2   DF627B     DELLDF_SUP_TON      SUP          TON
3   4ZB96A         HP4Z_PH_LJ       PH           LJ
4  0R0N0QB   DELL0R_PC_Laptop       PC       Laptop
5   7LE37B       DELL7L_PH_IJ       PH           IJ
6  89Z55QB  DELL89_PC_Desktop       PC      Desktop
7  8C4R9PA     HP8C_PC_Laptop       PC       Laptop
8   G0L15B     DELLG0_SUP_INK      SUP          INK
9   DF853B     DELLDF_SUP_TON      SUP          TON

In [68]:
category_df.columns = category_df.columns.str.strip().str.lower()

category_df.columns.tolist()

['sku', 'pl', 'category', 'sub_category']

In [69]:
for col in ["sku", "pl", "category", "sub_category"]:
    category_df[col] = (
        category_df[col]
        .astype("string")
        .str.strip()
    )

In [70]:
print("Total rows:", len(category_df))

print("Missing SKU:",
      category_df["sku"].isna().sum())

print("Missing PL:",
      category_df["pl"].isna().sum())

print("Missing Category:",
      category_df["category"].isna().sum())

print("Missing Sub_Category:",
      category_df["sub_category"].isna().sum())

Total rows: 1598
Missing SKU: 0
Missing PL: 0
Missing Category: 0
Missing Sub_Category: 0

In [71]:
print(category_df["category"].value_counts())

category
SUP    780
PC     640
PH     178
Name: count, dtype: Int64

In [72]:
print(category_df["sub_category"].value_counts())

sub_category
INK        426
Laptop     416
TON        326
Desktop    164
IJ          84
LJ          74
Monitor     60
UNK         28
SJ          20
Name: count, dtype: Int64

In [73]:
# 1. Clean PL table column names
pl_df.columns = pl_df.columns.str.strip().str.lower()

# Check columns
print(pl_df.columns.tolist())

['pl', 'sku', 'category', 'sub_category', 'lpp_sub_category', 'brand', 'lpp_percentage']

In [74]:
# 2. Map Category and Sub_Category into PL table

pl_df = pl_df.merge(
    category_df[["sku", "pl", "category", "sub_category"]],
    on=["sku", "pl"],
    how="left"
)

# 3. Check result
pl_df.head(10)

,pl,sku,category_x,sub_category_x,lpp_sub_category,brand,lpp_percentage,category_y,sub_category_y
0,DELL0X_PC_Laptop,0X749QB,PC,Laptop,Laptop,DELL,0.078,PC,Laptop
1,DELL75_PC_Monitor,75X62BB,PC,Monitor,Monitor,DELL,0.056,PC,Monitor
2,DELLDF_SUP_TON,DF627B,SUP,TON,Toner,DELL,0.023,SUP,TON
3,HP4Z_PH_LJ,4ZB96A,PH,LJ,Laserjet,HP,0.065,PH,LJ
4,DELL0R_PC_Laptop,0R0N0QB,PC,Laptop,Laptop,DELL,0.078,PC,Laptop
5,DELL7L_PH_IJ,7LE37B,PH,IJ,Inkjet,DELL,0.056,PH,IJ
6,DELL89_PC_Desktop,89Z55QB,PC,Desktop,Desktop,DELL,0.023,PC,Desktop
7,HP8C_PC_Laptop,8C4R9PA,PC,Laptop,Laptop,HP,0.034,PC,Laptop
8,DELLG0_SUP_INK,G0L15B,SUP,INK,Ink,DELL,0.035,SUP,INK
9,DELLDF_SUP_TON,DF853B,SUP,TON,Toner,DELL,0.023,SUP,TON

In [75]:
# Remove duplicate mapping columns
pl_df.drop(
    columns=["category_y", "sub_category_y"],
    inplace=True
)

# Rename the existing columns
pl_df.rename(
    columns={
        "category_x": "category",
        "sub_category_x": "sub_category"
    },
    inplace=True
)

# Check columns
print(pl_df.columns.tolist())

['pl', 'sku', 'category', 'sub_category', 'lpp_sub_category', 'brand', 'lpp_percentage']

In [76]:
print("Total rows:", len(pl_df))
print("Missing Category:", pl_df["category"].isna().sum())
print("Missing Sub_Category:", pl_df["sub_category"].isna().sum())

Total rows: 1598
Missing Category: 0
Missing Sub_Category: 0

In [77]:
pl_df[
    ["pl", "sku", "category", "sub_category",
     "lpp_sub_category", "brand", "lpp_percentage"]
].head(10)

,pl,sku,category,sub_category,lpp_sub_category,brand,lpp_percentage
0,DELL0X_PC_Laptop,0X749QB,PC,Laptop,Laptop,DELL,0.078
1,DELL75_PC_Monitor,75X62BB,PC,Monitor,Monitor,DELL,0.056
2,DELLDF_SUP_TON,DF627B,SUP,TON,Toner,DELL,0.023
3,HP4Z_PH_LJ,4ZB96A,PH,LJ,Laserjet,HP,0.065
4,DELL0R_PC_Laptop,0R0N0QB,PC,Laptop,Laptop,DELL,0.078
5,DELL7L_PH_IJ,7LE37B,PH,IJ,Inkjet,DELL,0.056
6,DELL89_PC_Desktop,89Z55QB,PC,Desktop,Desktop,DELL,0.023
7,HP8C_PC_Laptop,8C4R9PA,PC,Laptop,Laptop,HP,0.034
8,DELLG0_SUP_INK,G0L15B,SUP,INK,Ink,DELL,0.035
9,DELLDF_SUP_TON,DF853B,SUP,TON,Toner,DELL,0.023

### price_df_cleaning and mapping

In [78]:
price_df.columns.tolist()

['map',
 'pl',
 'sku',
 'brand',
 'category',
 'sub_category',
 'lpp_sub_category',
 'lpp_percentage',
 'lpp']

In [79]:
price_df.head(10)

,map,pl,sku,brand,category,sub_category,lpp_sub_category,lpp_percentage,lpp
0,106684,DELL0X_PC_Laptop,0X749QB,DELL,PC,Laptop,Laptop,0.078,98362.648
1,35611,DELL75_PC_Monitor,75X62BB,DELL,PC,Monitor,Monitor,0.056,33616.784
2,29914,DELLDF_SUP_TON,DF627B,DELL,SUP,TON,Toner,0.023,29225.978
3,39258,HP4Z_PH_LJ,4ZB96A,HP,PH,LJ,Laserjet,0.065,36706.230
4,139670,DELL0R_PC_Laptop,0R0N0QB,DELL,PC,Laptop,Laptop,0.078,128775.740
5,993854,DELL7L_PH_IJ,7LE37B,DELL,PH,IJ,Inkjet,0.056,938198.176
6,49687,DELL89_PC_Desktop,89Z55QB,DELL,PC,Desktop,Desktop,0.023,48544.199
7,102079,HP8C_PC_Laptop,8C4R9PA,HP,PC,Laptop,Laptop,0.034,98608.314
8,9900,DELLG0_SUP_INK,G0L15B,DELL,SUP,INK,Ink,0.035,9553.500
9,28788,DELLDF_SUP_TON,DF853B,DELL,SUP,TON,Toner,0.023,28125.876

In [80]:
# Price_df - clean column names
price_df.columns = (
    price_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(price_df.columns.tolist())

['map', 'pl', 'sku', 'brand', 'category', 'sub_category', 'lpp_sub_category', 'lpp_percentage', 'lpp']

In [81]:
# Clean string columns
for col in price_df.select_dtypes(include="object").columns:
    price_df[col] = (
        price_df[col]
        .astype("string")
        .str.strip()
    )

price_df.head(10)

,map,pl,sku,brand,category,sub_category,lpp_sub_category,lpp_percentage,lpp
0,106684,DELL0X_PC_Laptop,0X749QB,DELL,PC,Laptop,Laptop,0.078,98362.648
1,35611,DELL75_PC_Monitor,75X62BB,DELL,PC,Monitor,Monitor,0.056,33616.784
2,29914,DELLDF_SUP_TON,DF627B,DELL,SUP,TON,Toner,0.023,29225.978
3,39258,HP4Z_PH_LJ,4ZB96A,HP,PH,LJ,Laserjet,0.065,36706.230
4,139670,DELL0R_PC_Laptop,0R0N0QB,DELL,PC,Laptop,Laptop,0.078,128775.740
5,993854,DELL7L_PH_IJ,7LE37B,DELL,PH,IJ,Inkjet,0.056,938198.176
6,49687,DELL89_PC_Desktop,89Z55QB,DELL,PC,Desktop,Desktop,0.023,48544.199
7,102079,HP8C_PC_Laptop,8C4R9PA,HP,PC,Laptop,Laptop,0.034,98608.314
8,9900,DELLG0_SUP_INK,G0L15B,DELL,SUP,INK,Ink,0.035,9553.500
9,28788,DELLDF_SUP_TON,DF853B,DELL,SUP,TON,Toner,0.023,28125.876

In [82]:
print("Price rows:", len(price_df))

print("Missing SKU:", price_df["sku"].isna().sum())
print("Missing PL:", price_df["pl"].isna().sum())
print("Missing LPP:", price_df["lpp"].isna().sum())

Price rows: 1606
Missing SKU: 0
Missing PL: 0
Missing LPP: 48

In [83]:
print(
    "Duplicate SKU + PL:",
    price_df.duplicated(
        subset=["sku", "pl"],
        keep=False
    ).sum()
)

Duplicate SKU + PL: 16

In [84]:
price_df[
    price_df.duplicated(
        subset=["sku", "pl"],
        keep=False
    )
].sort_values(["sku", "pl"])

,map,pl,sku,brand,category,sub_category,lpp_sub_category,lpp_percentage,lpp
1363,98309,HP8F_PC_Desktop,8F6D4PA,HP,PC,Laptop,Laptop,0.034,94966.494
1364,98309,HP8F_PC_Desktop,8F6D4PA,HP,PC,Laptop,Laptop,0.034,94966.494
1252,102829,HP8F_PC_Laptop,8F6D4PA,HP,PC,Laptop,Laptop,0.034,99332.814
1253,102829,HP8F_PC_Laptop,8F6D4PA,HP,PC,Laptop,Laptop,0.034,99332.814
1026,154174,HP8L_PC_Desktop,8L120PA,HP,PC,Laptop,Laptop,0.034,148932.084
1027,154174,HP8L_PC_Desktop,8L120PA,HP,PC,Laptop,Laptop,0.034,148932.084
130,167879,HP8L_PC_Laptop,8L120PA,HP,PC,Laptop,Laptop,0.034,162171.114
131,167879,HP8L_PC_Laptop,8L120PA,HP,PC,Laptop,Laptop,0.034,162171.114
483,107159,HP8L_PC_Desktop,8L129PA,HP,PC,Desktop,Desktop,0.091,97407.531
484,107159,HP8L_PC_Desktop,8L129PA,HP,PC,Desktop,Desktop,0.091,97407.531
1060,106019,HP8L_PC_Laptop,8L129PA,HP,PC,Desktop,Desktop,0.091,96371.271
1061,106019,HP8L_PC_Laptop,8L129PA,HP,PC,Desktop,Desktop,0.091,96371.271
902,153749,HP8L_PC_Desktop,8L130PA,HP,PC,Desktop,Desktop,0.091,139757.841
903,153749,HP8L_PC_Desktop,8L130PA,HP,PC,Desktop,Desktop,0.091,139757.841
1315,152022,HP8L_PC_Laptop,8L130PA,HP,PC,Desktop,Desktop,0.091,138187.998
1316,152022,HP8L_PC_Laptop,8L130PA,HP,PC,Desktop,Desktop,0.091,138187.998

In [85]:

duplicate_lpp = (
    price_df
    .groupby(["sku", "pl"])["lpp"]
    .nunique()
)

duplicate_lpp[duplicate_lpp > 1]

Series([], Name: lpp, dtype: int64)

In [86]:
price_df = price_df.drop_duplicates(
    subset=["sku", "pl"],
    keep="first"
).copy()

In [87]:
print(
    "Duplicate SKU + PL after cleaning:",
    price_df.duplicated(
        subset=["sku", "pl"]
    ).sum()
)

Duplicate SKU + PL after cleaning: 0

In [88]:
price_map = price_df[
    ["sku", "pl", "lpp"]
].copy()

In [89]:
pl_df = pl_df.merge(
    price_map,
    on=["sku", "pl"],
    how="left",
    validate="one_to_one"
)

In [90]:
print("PL rows after price mapping:", len(pl_df))

print(
    "Missing LPP:",
    pl_df["lpp"].isna().sum()
)

pl_df.head(10)

PL rows after price mapping: 1598
Missing LPP: 48

,pl,sku,category,sub_category,lpp_sub_category,brand,lpp_percentage,lpp
0,DELL0X_PC_Laptop,0X749QB,PC,Laptop,Laptop,DELL,0.078,98362.648
1,DELL75_PC_Monitor,75X62BB,PC,Monitor,Monitor,DELL,0.056,33616.784
2,DELLDF_SUP_TON,DF627B,SUP,TON,Toner,DELL,0.023,29225.978
3,HP4Z_PH_LJ,4ZB96A,PH,LJ,Laserjet,HP,0.065,36706.230
4,DELL0R_PC_Laptop,0R0N0QB,PC,Laptop,Laptop,DELL,0.078,128775.740
5,DELL7L_PH_IJ,7LE37B,PH,IJ,Inkjet,DELL,0.056,938198.176
6,DELL89_PC_Desktop,89Z55QB,PC,Desktop,Desktop,DELL,0.023,48544.199
7,HP8C_PC_Laptop,8C4R9PA,PC,Laptop,Laptop,HP,0.034,98608.314
8,DELLG0_SUP_INK,G0L15B,SUP,INK,Ink,DELL,0.035,9553.500
9,DELLDF_SUP_TON,DF853B,SUP,TON,Toner,DELL,0.023,28125.876

In [100]:
# Remove rows where LPP is NULL
pl_df_clean = pl_df.dropna(subset=['lpp']).copy()

print("Original rows:", len(pl_df))
print("Cleaned rows:", len(pl_df_clean))
print("Remaining NULL LPP:", pl_df_clean['lpp'].isna().sum())

Original rows: 1598
Cleaned rows: 1550
Remaining NULL LPP: 0

In [101]:
pl_df_clean[pl_df_clean.isna().any(axis=1)]

Empty DataFrame
Columns: [pl, sku, category, sub_category, lpp_sub_category, brand, lpp_percentage, lpp]
Index: []

In [102]:
pl_df_clean.to_csv("pl_table_updated.csv", index=False)

print("Updated CSV saved successfully!")

Updated CSV saved successfully!

In [91]:
# Verify the 48 missing LPP records

missing_lpp = pl_df[pl_df["lpp"].isna()][
    ["sku", "pl", "category", "sub_category"]
]

print("Missing LPP rows:", len(missing_lpp))

missing_lpp.head(20)

Missing LPP rows: 48

         sku              pl category sub_category
18   L0R91AA    HPL0_SUP_UNK      SUP          UNK
94   7AE72BB  DELL7A_SUP_UNK      SUP          UNK
115   31H19B    DELL31_PH_SJ       PH           SJ
206   7GX17B    DELL7G_PH_SJ       PH           SJ
235   K4N82B  DELLK4_SUP_UNK      SUP          UNK
289   J3M68A    HPJ3_SUP_UNK      SUP          UNK
342  M1S05BB  DELLM1_SUP_UNK      SUP          UNK
370   7GX10B    DELL7G_PH_SJ       PH           SJ
372  L0S06AA    HPL0_SUP_UNK      SUP          UNK
424   31H17B    DELL31_PH_SJ       PH           SJ
454   6FW07A      HP6F_PH_SJ       PH           SJ
517   6FW09A      HP6F_PH_SJ       PH           SJ
539   20G07A      HP20_PH_SJ       PH           SJ
562   6FW10A      HP6F_PH_SJ       PH           SJ
617   6FW08A      HP6F_PH_SJ       PH           SJ
636  M1T17BB  DELLM1_SUP_UNK      SUP          UNK
640  L0R88AA    HPL0_SUP_UNK      SUP          UNK
684   7GX21B    DELL7G_PH_SJ       PH           SJ
685   20G05A      HP20_PH_SJ       PH           SJ
741   20G06A      HP20_PH_SJ       PH           SJ

In [92]:
# Check whether these SKU + PL keys exist in price_df

check_missing = missing_lpp.merge(
    price_df[["sku", "pl", "lpp"]],
    on=["sku", "pl"],
    how="left"
)

check_missing.head(20)

        sku              pl category sub_category  lpp
0   L0R91AA    HPL0_SUP_UNK      SUP          UNK  NaN
1   7AE72BB  DELL7A_SUP_UNK      SUP          UNK  NaN
2    31H19B    DELL31_PH_SJ       PH           SJ  NaN
3    7GX17B    DELL7G_PH_SJ       PH           SJ  NaN
4    K4N82B  DELLK4_SUP_UNK      SUP          UNK  NaN
5    J3M68A    HPJ3_SUP_UNK      SUP          UNK  NaN
6   M1S05BB  DELLM1_SUP_UNK      SUP          UNK  NaN
7    7GX10B    DELL7G_PH_SJ       PH           SJ  NaN
8   L0S06AA    HPL0_SUP_UNK      SUP          UNK  NaN
9    31H17B    DELL31_PH_SJ       PH           SJ  NaN
10   6FW07A      HP6F_PH_SJ       PH           SJ  NaN
11   6FW09A      HP6F_PH_SJ       PH           SJ  NaN
12   20G07A      HP20_PH_SJ       PH           SJ  NaN
13   6FW10A      HP6F_PH_SJ       PH           SJ  NaN
14   6FW08A      HP6F_PH_SJ       PH           SJ  NaN
15  M1T17BB  DELLM1_SUP_UNK      SUP          UNK  NaN
16  L0R88AA    HPL0_SUP_UNK      SUP          UNK  NaN
17   7GX21B    DELL7G_PH_SJ       PH           SJ  NaN
18   20G05A      HP20_PH_SJ       PH           SJ  NaN
19   20G06A      HP20_PH_SJ       PH           SJ  NaN

In [93]:
# Verify missing LPP by sub-category

print(
    pl_df[pl_df["lpp"].isna()]["sub_category"]
    .value_counts()
)

sub_category
UNK    28
SJ     20
Name: count, dtype: Int64

In [94]:
# Check LPP availability by sub-category

lpp_check = (
    pl_df.groupby("sub_category")["lpp"]
    .agg(
        total_rows="size",
        missing_lpp=lambda x: x.isna().sum()
    )
)

lpp_check

              total_rows  missing_lpp
sub_category
Desktop              164            0
IJ                    84            0
INK                  426            0
LJ                    74            0
Laptop               416            0
Monitor               60            0
SJ                    20           20
TON                  326            0
UNK                   28           28

In [95]:
# Final validation after price mapping

print("PL rows:", len(pl_df))
print("Missing SKU:", pl_df["sku"].isna().sum())
print("Missing PL:", pl_df["pl"].isna().sum())
print("Missing Category:", pl_df["category"].isna().sum())
print("Missing Sub_Category:", pl_df["sub_category"].isna().sum())
print("Missing LPP:", pl_df["lpp"].isna().sum())

print("\nFinal columns:")
print(pl_df.columns.tolist())

PL rows: 1598
Missing SKU: 0
Missing PL: 0
Missing Category: 0
Missing Sub_Category: 0
Missing LPP: 48

Final columns:
['pl', 'sku', 'category', 'sub_category', 'lpp_sub_category', 'brand', 'lpp_percentage', 'lpp']

In [96]:
# Save final cleaned PL dataset

pl_df.to_csv("PL_TABLE_CLEANED_MAPPED.csv", index=False)

print("PL cleaned dataset saved successfully.")
print("Rows:", len(pl_df))
print("Columns:", pl_df.columns.tolist())

PL cleaned dataset saved successfully.
Rows: 1598
Columns: ['pl', 'sku', 'category', 'sub_category', 'lpp_sub_category', 'brand', 'lpp_percentage', 'lpp']

### sql connection....

In [97]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (2.0.54)
Requirement already satisfied: pymysql in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (1.2.3)
Requirement already satisfied: greenlet>=1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [98]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:YOUR_PASSWORD@localhost/YOUR_DATABASE"
)

print("MySQL connection successful!")

MySQL connection successful!

In [99]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:srikutty001@localhost:3306/data_analysis"
)

In [112]:
with engine.connect() as conn:
    print("MySQL connection successful!")

MySQL connection successful!

In [252]:
# Load cleaned PL dataset into MySQL

pl_df.to_sql(
    name="pl_table",
    con=engine,
    if_exists="replace",
    index=False
)

print("PL table loaded successfully!")

PL table loaded successfully!

In [253]:
with engine.connect() as conn:
    result = conn.exec_driver_sql("SELECT COUNT(*) FROM pl_table")
    print("Rows in MySQL:", result.fetchone()[0])

Rows in MySQL: 1598

In [254]:
with engine.connect() as conn:
    result = conn.exec_driver_sql("DESCRIBE pl_table")
    for row in result:
        print(row)

('pl', 'text', 'YES', '', None, '')
('sku', 'text', 'YES', '', None, '')
('category', 'text', 'YES', '', None, '')
('sub_category', 'text', 'YES', '', None, '')
('lpp_sub_category', 'text', 'YES', '', None, '')
('brand', 'text', 'YES', '', None, '')
('lpp_percentage', 'double', 'YES', '', None, '')
('lpp', 'double', 'YES', '', None, '')

In [255]:
with engine.connect() as conn:
    result = conn.exec_driver_sql("""
        SELECT *
        FROM pl_table
        LIMIT 10
    """)

    for row in result:
        print(row)

('DELL0X_PC_Laptop', '0X749QB', 'PC', 'Laptop', 'Laptop', 'DELL', 0.078, 98362.648)
('DELL75_PC_Monitor', '75X62BB', 'PC', 'Monitor', 'Monitor', 'DELL', 0.056, 33616.784)
('DELLDF_SUP_TON', 'DF627B', 'SUP', 'TON', 'Toner', 'DELL', 0.023, 29225.978)
('HP4Z_PH_LJ', '4ZB96A', 'PH', 'LJ', 'Laserjet', 'HP', 0.065, 36706.23)
('DELL0R_PC_Laptop', '0R0N0QB', 'PC', 'Laptop', 'Laptop', 'DELL', 0.078, 128775.74)
('DELL7L_PH_IJ', '7LE37B', 'PH', 'IJ', 'Inkjet', 'DELL', 0.056, 938198.176)
('DELL89_PC_Desktop', '89Z55QB', 'PC', 'Desktop', 'Desktop', 'DELL', 0.023, 48544.199)
('HP8C_PC_Laptop', '8C4R9PA', 'PC', 'Laptop', 'Laptop', 'HP', 0.034, 98608.314)
('DELLG0_SUP_INK', 'G0L15B', 'SUP', 'INK', 'Ink', 'DELL', 0.035, 9553.5)
('DELLDF_SUP_TON', 'DF853B', 'SUP', 'TON', 'Toner', 'DELL', 0.023, 28125.876)

In [256]:
with engine.connect() as conn:
    result = conn.exec_driver_sql("""
        SELECT COUNT(*) AS total_rows
        FROM pl_table
    """)

    print(result.fetchone())

(1598,)

In [103]:
sku_df.to_csv("sku_table_updated_1.csv", index=False)

print("Updated CSV saved successfully!")

Updated CSV saved successfully!

In [257]:
sku_df.to_sql(
    name="sku_table",
    con=engine,
    if_exists="replace",
    index=False
)

print("Price table loaded successfully!")

Price table loaded successfully!

In [258]:
seller_mapping_df.to_sql(
    name="seller_mapping_table",
    con=engine,
    if_exists="replace",
    index=False
)

print("Price tabletable loaded successfully!")

Price table loaded successfully!

In [104]:
price_df.head()

,map,pl,sku,brand,category,sub_category,lpp_sub_category,lpp_percentage,lpp
0,106684,DELL0X_PC_Laptop,0X749QB,DELL,PC,Laptop,Laptop,0.078,98362.648
1,35611,DELL75_PC_Monitor,75X62BB,DELL,PC,Monitor,Monitor,0.056,33616.784
2,29914,DELLDF_SUP_TON,DF627B,DELL,SUP,TON,Toner,0.023,29225.978
3,39258,HP4Z_PH_LJ,4ZB96A,HP,PH,LJ,Laserjet,0.065,36706.230
4,139670,DELL0R_PC_Laptop,0R0N0QB,DELL,PC,Laptop,Laptop,0.078,128775.740

In [107]:
# Keep only the required columns
price_list_df = price_df[['pl', 'sku','map', 'lpp']].copy()

# Remove rows where LPP is NULL
price_list_df = price_list_df.dropna(subset=['lpp']).copy()

# Check the result
print("Rows:", len(price_list_df))
print("Columns:", price_list_df.columns.tolist())

price_list_df.head()

Rows: 1550
Columns: ['pl', 'sku', 'map', 'lpp']

                  pl      sku     map         lpp
0   DELL0X_PC_Laptop  0X749QB  106684   98362.648
1  DELL75_PC_Monitor  75X62BB   35611   33616.784
2     DELLDF_SUP_TON   DF627B   29914   29225.978
3         HP4Z_PH_LJ   4ZB96A   39258   36706.230
4   DELL0R_PC_Laptop  0R0N0QB  139670  128775.740

In [108]:
price_list_df.to_sql(
    name="price_list_table",
    con=engine,
    if_exists="replace",
    index=False
)

print("Price_list_table loaded successfully!")

Price_list_table loaded successfully!

In [109]:
price_list_df.to_csv("price_list_table_updated_4.csv", index=False)

print("Updated CSV saved successfully!")

Updated CSV saved successfully!

In [118]:
category_df=category_df[['category','sub_category','pl','sku']].copy()

In [119]:
category_df.head

<bound method NDFrame.head of      category sub_category                 pl      sku
0          PC       Laptop   DELL0X_PC_Laptop  0X749QB
1          PC      Monitor  DELL75_PC_Monitor  75X62BB
2         SUP          TON     DELLDF_SUP_TON   DF627B
3          PH           LJ         HP4Z_PH_LJ   4ZB96A
4          PC       Laptop   DELL0R_PC_Laptop  0R0N0QB
...       ...          ...                ...      ...
1593      SUP          INK     DELL4K_SUP_INK  4KB93BB
1594      SUP          TON     DELLX2_SUP_TON   X2231B
1595      SUP          INK       HPB3_SUP_INK   B3P21A
1596       PC      Desktop  DELL78_PC_Desktop  78X20QB
1597      SUP          TON       HPCF_SUP_TON   CF364A

[1598 rows x 4 columns]>

In [120]:
print(category_df.columns.tolist())

['category', 'sub_category', 'pl', 'sku']

In [123]:
from IPython.display import display

display(category_df)

     category sub_category                 pl      sku
0          PC       Laptop   DELL0X_PC_Laptop  0X749QB
1          PC      Monitor  DELL75_PC_Monitor  75X62BB
2         SUP          TON     DELLDF_SUP_TON   DF627B
3          PH           LJ         HP4Z_PH_LJ   4ZB96A
4          PC       Laptop   DELL0R_PC_Laptop  0R0N0QB
...       ...          ...                ...      ...
1593      SUP          INK     DELL4K_SUP_INK  4KB93BB
1594      SUP          TON     DELLX2_SUP_TON   X2231B
1595      SUP          INK       HPB3_SUP_INK   B3P21A
1596       PC      Desktop  DELL78_PC_Desktop  78X20QB
1597      SUP          TON       HPCF_SUP_TON   CF364A

[1598 rows x 4 columns]

In [124]:
category_df.to_excel(
    "category_mapping_table_updated_5.xlsx",
    index=False
)

In [125]:
# Check SJ and UNK entries
sj_unk_df = category_df[
    category_df['sub_category'].astype(str).str.strip().str.upper().isin(['SJ', 'UNK'])
]

print("SJ + UNK entries:", len(sj_unk_df))

SJ + UNK entries: 48

In [126]:
category_df = category_df[
    ~category_df['sub_category'].astype(str).str.strip().str.upper().isin(['SJ', 'UNK'])
].copy()

In [127]:
print("Rows after removal:", len(category_df))
print("Remaining SJ/UNK:",
      category_df['sub_category'].astype(str).str.strip().str.upper().isin(['SJ', 'UNK']).sum())

Rows after removal: 1550
Remaining SJ/UNK: 0

In [128]:
category_df.to_excel(
    "category_mapping_table_updated_5.xlsx",
    index=False
)

In [129]:
category_df.to_sql(
    name="category_mapping_table",
    con=engine,
    if_exists="replace",
    index=False
)

print("Cleaned category_mapping_table uploaded successfully!")

Cleaned category_mapping_table uploaded successfully!

### createing to the promotion table

In [130]:
price_df["lpp"] = (
    price_df["map"] * (1 - price_df["lpp_percentage"])
)

In [131]:
price_df[[
    "sku",
    "map",
    "lpp_percentage",
    "lpp"
]].head(10)

       sku     map  lpp_percentage         lpp
0  0X749QB  106684           0.078   98362.648
1  75X62BB   35611           0.056   33616.784
2   DF627B   29914           0.023   29225.978
3   4ZB96A   39258           0.065   36706.230
4  0R0N0QB  139670           0.078  128775.740
5   7LE37B  993854           0.056  938198.176
6  89Z55QB   49687           0.023   48544.199
7  8C4R9PA  102079           0.034   98608.314
8   G0L15B    9900           0.035    9553.500
9   DF853B   28788           0.023   28125.876

### now created to the q4 offers

In [132]:
q4_offer = {
    "SUP": "20% off ink",
    "PH": "$10 off laser jet",
    "PC": "15% off"
}

### load tham promotional sku

In [133]:
promo_raw = pd.read_excel(
    "PROMOTION_TABLE_6.xlsx",
    header=None
)

promo_raw.head(20)

,0,1,2,3,4,5,6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Promotion Table,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Offer table,NaN,NaN,NaN,NaN,NaN
6,NaN,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct),NaN
7,NaN,Supply,10% off ink,$2 off toner,5% off toner,20% off ink,NaN
8,NaN,Print Hardware,15% off ink jet,Free setup service,2% off scanners,$10 off laser jet,NaN
9,NaN,PC,$10 off laptops,Free accessories,Free accessories,15 % off,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Promotional SKUs,NaN,NaN,NaN,NaN,NaN
14,NaN,For the SKU Below,NaN,NaN,NaN,NaN,NaN
15,NaN,G0L15B,NaN,NaN,NaN,NaN,NaN
16,NaN,7Y4T6QB,NaN,PL,SKU,Season,Promotion
17,NaN,4K0V8PA,NaN,DELLOX_PC_LAPTOP,CN635A,Q3,2000
18,NaN,385Z7PA,NaN,NaN,NaN,NaN,NaN
19,NaN,T6M05AA,NaN,NaN,NaN,NaN,NaN

In [134]:
offer_df = promo_raw.iloc[6:10, 1:6].copy()

offer_df.columns = [
    "Category",
    "Q1",
    "Q2",
    "Q3",
    "Q4"
]

offer_df = offer_df.dropna(subset=["Category"])

offer_df

,Category,Q1,Q2,Q3,Q4
6,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct)
7,Supply,10% off ink,$2 off toner,5% off toner,20% off ink
8,Print Hardware,15% off ink jet,Free setup service,2% off scanners,$10 off laser jet
9,PC,$10 off laptops,Free accessories,Free accessories,15 % off

In [135]:
q4_offer = dict(
    zip(
        offer_df["Category"],
        offer_df["Q4"]
    )
)

q4_offer

{'Category': 'Q4 (Aug-Oct)',
 'Supply': '20% off  ink',
 'Print Hardware': '$10 off laser jet ',
 'PC': '15 % off'}

In [136]:
category_map = {
    "SUP": "Supply",
    "PH": "Print Hardware",
    "PC": "PC"
}

In [137]:
price_df["offer_category"] = price_df["category"].map(category_map)

In [138]:
price_df[
    ["sku", "category", "offer_category"]
].head(10)

       sku category  offer_category
0  0X749QB       PC              PC
1  75X62BB       PC              PC
2   DF627B      SUP          Supply
3   4ZB96A       PH  Print Hardware
4  0R0N0QB       PC              PC
5   7LE37B       PH  Print Hardware
6  89Z55QB       PC              PC
7  8C4R9PA       PC              PC
8   G0L15B      SUP          Supply
9   DF853B      SUP          Supply

In [139]:
price_df["q4_promotion"] = (
    price_df["offer_category"].map(q4_offer)
)

In [140]:
price_df[
    ["sku", "category", "offer_category", "q4_promotion"]
].head(20)

        sku category  offer_category        q4_promotion
0   0X749QB       PC              PC            15 % off
1   75X62BB       PC              PC            15 % off
2    DF627B      SUP          Supply        20% off  ink
3    4ZB96A       PH  Print Hardware  $10 off laser jet
4   0R0N0QB       PC              PC            15 % off
5    7LE37B       PH  Print Hardware  $10 off laser jet
6   89Z55QB       PC              PC            15 % off
7   8C4R9PA       PC              PC            15 % off
8    G0L15B      SUP          Supply        20% off  ink
9    DF853B      SUP          Supply        20% off  ink
10  CN045AA      SUP          Supply        20% off  ink
11  C2P23AA      SUP          Supply        20% off  ink
12  C2P21AA      SUP          Supply        20% off  ink
13   4FE79B      SUP          Supply        20% off  ink
14   DG460B      SUP          Supply        20% off  ink
15  8F6C9PA       PC              PC            15 % off
16  4K0V9PA      SUP          Supply        20% off  ink
17  8F8Z8PA       PC              PC            15 % off
18  L0R91AA      SUP          Supply        20% off  ink
19   T8W15A       PH  Print Hardware  $10 off laser jet

In [141]:
promo_table = promo_raw.iloc[16:, 3:7].copy()

promo_table.columns = [
    "PL",
    "SKU",
    "Season",
    "Promotion"
]

promo_table = promo_table.dropna(
    subset=["PL", "SKU"],
    how="any"
)

promo_table.head(20)

                  PL     SKU  Season  Promotion
16                PL     SKU  Season  Promotion
17  DELLOX_PC_LAPTOP  CN635A      Q3       2000

In [142]:
print("Promotion rows:", len(promo_table))

print("\nMissing values:")
print(promo_table.isna().sum())

print("\nPromotion table:")
display(promo_table.head(20))

Promotion rows: 2

Missing values:
PL           0
SKU          0
Season       0
Promotion    0
dtype: int64

Promotion table:

                  PL     SKU  Season  Promotion
16                PL     SKU  Season  Promotion
17  DELLOX_PC_LAPTOP  CN635A      Q3       2000

In [143]:
# Extract promotional SKU list
promo_skus = promo_raw.iloc[15:, 1].copy()

# Remove empty values
promo_skus = promo_skus.dropna()

# Convert to string and clean
promo_skus = promo_skus.astype(str).str.strip()

# Remove section/header text
promo_skus = promo_skus[
    ~promo_skus.str.contains(
        "Promotional SKUs|For the SKU Below|SKU",
        case=False,
        na=False
    )
]

# Remove duplicates
promo_skus = promo_skus.drop_duplicates().reset_index(drop=True)

print("Promotional SKU count:", len(promo_skus))
print(promo_skus.head(20))

Promotional SKU count: 100
0      G0L15B
1     7Y4T6QB
2     4K0V8PA
3     385Z7PA
4     T6M05AA
5      C4Q32B
6     03V96QB
7      509O6B
8     952X8QB
9     R3723BG
10    6X4B9PA
11    3YM22AA
12     3ED50A
13    780A5PA
14    935M7QB
15    8L164PA
16     Z7Y83A
17     CF501A
18    9D3N5PA
19     U9X27B
Name: 1, dtype: object

In [144]:
promo_sku_df = pd.DataFrame({
    "SKU": promo_skus
})

promo_sku_df.head(20)

        SKU
0    G0L15B
1   7Y4T6QB
2   4K0V8PA
3   385Z7PA
4   T6M05AA
5    C4Q32B
6   03V96QB
7    509O6B
8   952X8QB
9   R3723BG
10  6X4B9PA
11  3YM22AA
12   3ED50A
13  780A5PA
14  935M7QB
15  8L164PA
16   Z7Y83A
17   CF501A
18  9D3N5PA
19   U9X27B

In [145]:
promo_df = promo_sku_df.merge(
    price_df[
        ["sku", "pl", "category"]
    ],
    left_on="SKU",
    right_on="sku",
    how="left"
)

promo_df = promo_df.drop(columns=["sku"])

promo_df.head(20)

        SKU                 pl category
0    G0L15B     DELLG0_SUP_INK      SUP
1   7Y4T6QB  DELL7Y_PC_Desktop       PC
2   4K0V8PA       HP4K_SUP_INK      SUP
3   385Z7PA    HP38_PC_Desktop       PC
4   T6M05AA       HPT6_SUP_INK      SUP
5    C4Q32B     DELLC4_SUP_INK      SUP
6   03V96QB   DELL03_PC_Laptop       PC
7    509O6B     DELL50_SUP_INK      SUP
8   952X8QB   DELL95_PC_Laptop       PC
9   R3723BG     DELLR3_SUP_TON      SUP
10  6X4B9PA    HP6X_PC_Desktop       PC
11  3YM22AA       HP3Y_SUP_INK      SUP
12   3ED50A       HP3E_SUP_INK      SUP
13  780A5PA    HP78_PC_Desktop       PC
14  935M7QB   DELL93_PC_Laptop       PC
15  8L164PA     HP8L_PC_Laptop       PC
16   Z7Y83A       HPZ7_SUP_TON      SUP
17   CF501A       HPCF_SUP_TON      SUP
18  9D3N5PA     HP9D_PC_Laptop       PC
19   U9X27B       DELLU9_PH_IJ       PH

In [146]:
print("Total promotional SKUs:", len(promo_df))

print(
    "SKUs without PL:",
    promo_df["pl"].isna().sum()
)

print(
    "SKUs without Category:",
    promo_df["category"].isna().sum()
)

Total promotional SKUs: 100
SKUs without PL: 0
SKUs without Category: 0

In [147]:
category_map = {
    "SUP": "Supply",
    "PH": "Print Hardware",
    "PC": "PC"
}

In [148]:
promo_df["offer_category"] = promo_df["category"].map(category_map)

In [149]:
q4_offer

{'Category': 'Q4 (Aug-Oct)',
 'Supply': '20% off  ink',
 'Print Hardware': '$10 off laser jet ',
 'PC': '15 % off'}

In [150]:
promo_df["Season"] = "Q4"

promo_df["Promotion"] = (
    promo_df["offer_category"].map(q4_offer)
)

In [151]:
promotion_table = promo_df[
    ["pl", "SKU", "Season", "Promotion"]
].copy()

promotion_table.columns = [
    "PL",
    "SKU",
    "Season",
    "Promotion"
]

In [152]:
promotion_table.head(20)

                   PL      SKU Season           Promotion
0      DELLG0_SUP_INK   G0L15B     Q4        20% off  ink
1   DELL7Y_PC_Desktop  7Y4T6QB     Q4            15 % off
2        HP4K_SUP_INK  4K0V8PA     Q4        20% off  ink
3     HP38_PC_Desktop  385Z7PA     Q4            15 % off
4        HPT6_SUP_INK  T6M05AA     Q4        20% off  ink
5      DELLC4_SUP_INK   C4Q32B     Q4        20% off  ink
6    DELL03_PC_Laptop  03V96QB     Q4            15 % off
7      DELL50_SUP_INK   509O6B     Q4        20% off  ink
8    DELL95_PC_Laptop  952X8QB     Q4            15 % off
9      DELLR3_SUP_TON  R3723BG     Q4        20% off  ink
10    HP6X_PC_Desktop  6X4B9PA     Q4            15 % off
11       HP3Y_SUP_INK  3YM22AA     Q4        20% off  ink
12       HP3E_SUP_INK   3ED50A     Q4        20% off  ink
13    HP78_PC_Desktop  780A5PA     Q4            15 % off
14   DELL93_PC_Laptop  935M7QB     Q4            15 % off
15     HP8L_PC_Laptop  8L164PA     Q4            15 % off
16       HPZ7_SUP_TON   Z7Y83A     Q4        20% off  ink
17       HPCF_SUP_TON   CF501A     Q4        20% off  ink
18     HP9D_PC_Laptop  9D3N5PA     Q4            15 % off
19       DELLU9_PH_IJ   U9X27B     Q4  $10 off laser jet

In [153]:
print("Promotion rows:", len(promotion_table))

print("\nMissing values:")
print(promotion_table.isna().sum())

print("\nDuplicate SKUs:")
print(promotion_table["SKU"].duplicated().sum())

display(promotion_table.head(20))

Promotion rows: 100

Missing values:
PL           0
SKU          0
Season       0
Promotion    0
dtype: int64

Duplicate SKUs:
0

                   PL      SKU Season           Promotion
0      DELLG0_SUP_INK   G0L15B     Q4        20% off  ink
1   DELL7Y_PC_Desktop  7Y4T6QB     Q4            15 % off
2        HP4K_SUP_INK  4K0V8PA     Q4        20% off  ink
3     HP38_PC_Desktop  385Z7PA     Q4            15 % off
4        HPT6_SUP_INK  T6M05AA     Q4        20% off  ink
5      DELLC4_SUP_INK   C4Q32B     Q4        20% off  ink
6    DELL03_PC_Laptop  03V96QB     Q4            15 % off
7      DELL50_SUP_INK   509O6B     Q4        20% off  ink
8    DELL95_PC_Laptop  952X8QB     Q4            15 % off
9      DELLR3_SUP_TON  R3723BG     Q4        20% off  ink
10    HP6X_PC_Desktop  6X4B9PA     Q4            15 % off
11       HP3Y_SUP_INK  3YM22AA     Q4        20% off  ink
12       HP3E_SUP_INK   3ED50A     Q4        20% off  ink
13    HP78_PC_Desktop  780A5PA     Q4            15 % off
14   DELL93_PC_Laptop  935M7QB     Q4            15 % off
15     HP8L_PC_Laptop  8L164PA     Q4            15 % off
16       HPZ7_SUP_TON   Z7Y83A     Q4        20% off  ink
17       HPCF_SUP_TON   CF501A     Q4        20% off  ink
18     HP9D_PC_Laptop  9D3N5PA     Q4            15 % off
19       DELLU9_PH_IJ   U9X27B     Q4  $10 off laser jet

### load to the dataset

In [154]:
promotion_table.to_sql(
    name="promotion_table",
    con=engine,
    if_exists="replace",
    index=False
)

print("promotion table loaded successfully!")

promotion table loaded successfully!

In [155]:
promotion_table.to_excel(
    "promotion_table_updated_6.xlsx",
    index=False
)

In [1]:
import pandas as pd

In [3]:
seller_mapping_table = pd.read_csv("seller_mapping_table_updated.csv")

print("Rows:", len(seller_mapping_table))
print(seller_mapping_table.head())
print(seller_mapping_table.columns)

Rows: 9860
       SKU Marketplace                                        Seller_name  \
0  6X3W4PA    Flipkart  H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction )
1  81H48PA    Flipkart                                          SHOP 24/7
2   676M7A        eBay                                             OPSUZY
3   CF361A        eBay                                         Abbey Edge
4   P2V25A    Snapdeal                                          ASTraders

  region  adv_price  Screenshot  live_link
0    USA    460.440         NaN        NaN
1    USA    940.200         NaN        NaN
2    UAE    651.640         NaN        NaN
3     UK    202.382         NaN        NaN
4    UAE    368.280         NaN        NaN
Index(['SKU', 'Marketplace', 'Seller_name', 'region', 'adv_price',
       'Screenshot', 'live_link'],
      dtype='object')

In [4]:
# Remove unwanted columns
seller_mapping_table = seller_mapping_table.drop(
    columns=["Screenshot", "live_link"]
)

print(seller_mapping_table.columns)
print("Rows:", len(seller_mapping_table))

Index(['SKU', 'Marketplace', 'Seller_name', 'region', 'adv_price'], dtype='object')
Rows: 9860

In [5]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (2.0.54)
Requirement already satisfied: pymysql in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (1.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.5.6)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
from sqlalchemy import create_engine

In [8]:
engine = create_engine(
    "mysql+pymysql://root:srikutty001@localhost:3306/data_analysis"
)

In [9]:
try:
    with engine.connect() as connection:
        print("MySQL connection successful!")
except Exception as e:
    print("Connection failed:", e)

MySQL connection successful!

In [10]:
seller_mapping_table.to_sql(
    name="seller_mapping_table",
    con=engine,
    if_exists="replace",
    index=False
)

print("Seller mapping table loaded successfully!")

Seller mapping table loaded successfully!

In [11]:
seller_mapping_table.head()

,SKU,Marketplace,Seller_name,region,adv_price
0,6X3W4PA,Flipkart,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),USA,460.440
1,81H48PA,Flipkart,SHOP 24/7,USA,940.200
2,676M7A,eBay,OPSUZY,UAE,651.640
3,CF361A,eBay,Abbey Edge,UK,202.382
4,P2V25A,Snapdeal,ASTraders,UAE,368.280

### 1.created to the price moinitering table.

In [156]:
import pandas as pd

sku = pd.read_csv("sku_table_updated_1.csv")
pl = pd.read_csv("pl_table_updated_2.csv")
seller = pd.read_csv("seller_mapping_table_updated_3.csv")
price = pd.read_csv("price_list_table_updated_4.csv")
category = pd.read_excel("category_mapping_table_updated_5.xlsx")
promotion = pd.read_excel("promotion_table_updated_6.xlsx")

### 2.created to the new price_monitering_table

In [157]:
pm = (seller
      .merge(pl[['sku','pl','lpp']], left_on='SKU', right_on='sku', how='inner')
      .merge(category[['sku','pl','category','sub_category']], on=['sku','pl'], how='left')
      .merge(price[['sku','pl','map']], on=['sku','pl'], how='left')
      .merge(promotion.rename(columns={'SKU':'sku','PL':'pl'})
             [['sku','pl','Season','Promotion']], on=['sku','pl'], how='left'))

### 3.create to the required column.

In [158]:
pm['Violation_date'] = pd.Timestamp.today().normalize()
pm['MAP_Price'] = pm['map']
pm['Advertised_price'] = pm['adv_price']

pm['Promotional_price'] = pd.NA
pm.loc[pm['Promotion'].eq('20% off  ink'), 'Promotional_price'] = pm['MAP_Price'] * 0.80
pm.loc[pm['Promotion'].eq('15 % off'), 'Promotional_price'] = pm['MAP_Price'] * 0.85
pm.loc[pm['Promotion'].eq('$10 off laser jet'), 'Promotional_price'] = pm['MAP_Price'] - 10

### 4.keep only you required column.

In [159]:
price_monitoring = pm[['SKU','Violation_date','pl','category','sub_category',
                       'region','Marketplace','Seller_name','MAP_Price','lpp',
                       'Advertised_price','Season','Promotional_price']]

price_monitoring.columns = [
    'SKU','Violation_date','PL','Category','Sub_category',
    'Region','Marketplace','Seller_name','MAP_Price','LPP',
    'Advertised_price','Season','Promotional_price'
]

### 5.analysis before saving.

In [160]:
print("Rows:", len(price_monitoring))
print("Columns:", price_monitoring.columns.tolist())
print(price_monitoring.head())
print(price_monitoring.isnull().sum())

Rows: 9661
Columns: ['SKU', 'Violation_date', 'PL', 'Category', 'Sub_category', 'Region', 'Marketplace', 'Seller_name', 'MAP_Price', 'LPP', 'Advertised_price', 'Season', 'Promotional_price']
       SKU Violation_date               PL Category Sub_category Region  \
0  6X3W4PA     2026-10-03  HP6X_PC_Desktop       PC      Desktop    USA
1  81H48PA     2026-10-03   HP81_PC_Laptop       PC       Laptop    USA
2   676M7A     2026-10-03     HP67_SUP_INK      SUP          INK    UAE
3   CF361A     2026-10-03     HPCF_SUP_TON      SUP          TON     UK
4   P2V25A     2026-10-03     HPP2_SUP_INK      SUP          INK    UAE

  Marketplace                                        Seller_name  MAP_Price  \
0    Flipkart  H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction )      33369
1    Flipkart                                          SHOP 24/7      73919
2        eBay                                             OPSUZY      13461
3        eBay                                         Abbey Edge      19396
4    Snapdeal                                          ASTraders       7752

         LPP  Advertised_price Season Promotional_price
0  30332.421           460.440    NaN              <NA>
1  71405.754           940.200    NaN              <NA>
2  12586.035           651.640    NaN              <NA>
3  17630.964           202.382    NaN              <NA>
4   7248.120           368.280    NaN              <NA>
SKU                     0
Violation_date          0
PL                      0
Category                0
Sub_category            0
Region                  0
Marketplace             0
Seller_name             0
MAP_Price               0
LPP                     0
Advertised_price        0
Season               9022
Promotional_price    9059
dtype: int64

In [161]:
print("Duplicate rows:", price_monitoring.duplicated().sum())

Duplicate rows: 0

In [164]:
price_monitoring

,SKU,Violation_date,PL,Category,Sub_category,Region,Marketplace,Seller_name,MAP_Price,LPP,Advertised_price,Season,Promotional_price
0,6X3W4PA,2026-10-03,HP6X_PC_Desktop,PC,Desktop,USA,Flipkart,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),33369,30332.421,460.440,NaN,<NA>
1,81H48PA,2026-10-03,HP81_PC_Laptop,PC,Laptop,USA,Flipkart,SHOP 24/7,73919,71405.754,940.200,NaN,<NA>
2,676M7A,2026-10-03,HP67_SUP_INK,SUP,INK,UAE,eBay,OPSUZY,13461,12586.035,651.640,NaN,<NA>
3,CF361A,2026-10-03,HPCF_SUP_TON,SUP,TON,UK,eBay,Abbey Edge,19396,17630.964,202.382,NaN,<NA>
4,P2V25A,2026-10-03,HPP2_SUP_INK,SUP,INK,UAE,Snapdeal,ASTraders,7752,7248.120,368.280,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9656,2W953PA,2026-10-03,HP2W_PC_Desktop,PC,Desktop,UK,Amazon,ELEMENT ENTERPRISES,41157,37411.713,429.392,NaN,<NA>
9657,8F6C4PA,2026-10-03,HP8F_PC_Laptop,PC,Laptop,UAE,Amazon,Vidya Books A'bad,160379,154926.114,7762.480,NaN,<NA>
9658,9U2C4PA,2026-10-03,HP9U_PC_Laptop,PC,Laptop,IND,Amazon,HIRVAX,142099,137267.634,152050.000,NaN,<NA>
9659,8Q3X5PA,2026-10-03,HP8Q_PC_Laptop,PC,Laptop,USA,eBay,SAM ENTERPRISE COLLECTION,46324,44748.984,378.000,NaN,<NA>
9660,8L147PA,2026-10-03,HP8L_PC_Laptop,PC,Laptop,CAN,Amazon,ASTITA,272087,262836.042,4832.320,NaN,<NA>

### 5.attach to the promotion also

In [166]:
print(promotion.columns)

Index(['PL', 'SKU', 'Season', 'Promotion'], dtype='object')

In [167]:
promotion.columns = promotion.columns.str.strip().str.upper()

In [169]:
print(price_monitoring.columns.tolist())

['SKU', 'Violation_date', 'PL', 'Category', 'Sub_category', 'Region', 'Marketplace', 'Seller_name', 'MAP_Price', 'LPP', 'Advertised_price', 'Season', 'Promotional_price']

In [170]:
price_monitoring = price_monitoring.merge(
    pl_table[['PL','SKU']],
    on='PL',
    how='left'
)

NameError: name 'pl_table' is not defined

In [171]:
pl_table = pd.read_sql("SELECT PL, SKU FROM pl_table", engine)

In [172]:
price_monitoring = price_monitoring.merge(
    pl_table,
    on=['PL', 'SKU'],
    how='left'
)

In [173]:
price_monitoring = price_monitoring.merge(
    promotion[['PL', 'SKU', 'SEASON', 'PROMOTION']],
    on=['PL', 'SKU'],
    how='left'
)

In [174]:
print(price_monitoring[['SKU','PL','SEASON','PROMOTION']].head())

       SKU               PL SEASON PROMOTION
0  6X3W4PA  HP6X_PC_Desktop    NaN       NaN
1  81H48PA   HP81_PC_Laptop    NaN       NaN
2   676M7A     HP67_SUP_INK    NaN       NaN
3   CF361A     HPCF_SUP_TON    NaN       NaN
4   P2V25A     HPP2_SUP_INK    NaN       NaN

In [175]:
for df in [price_monitoring, promotion]:
    df[['PL','SKU']] = df[['PL','SKU']].astype(str).apply(lambda x: x.str.strip())

price_monitoring = price_monitoring.drop(columns=['SEASON','PROMOTION'], errors='ignore')

price_monitoring = price_monitoring.merge(
    promotion[['PL','SKU','SEASON','PROMOTION']],
    on=['PL','SKU'], how='left'
)

In [176]:
price_monitoring[['SKU','PL','SEASON','PROMOTION']].head(10)

       SKU               PL SEASON PROMOTION
0  6X3W4PA  HP6X_PC_Desktop    NaN       NaN
1  81H48PA   HP81_PC_Laptop    NaN       NaN
2   676M7A     HP67_SUP_INK    NaN       NaN
3   CF361A     HPCF_SUP_TON    NaN       NaN
4   P2V25A     HPP2_SUP_INK    NaN       NaN
5   3WX30A     HP3W_SUP_INK    NaN       NaN
6  64X69AA  HP64_PC_Monitor    NaN       NaN
7  9U7H2PA   HP9U_PC_Laptop    NaN       NaN
8  64V81AA  HP64_PC_Monitor    NaN       NaN
9   Z7Y79A     HPZ7_SUP_TON    NaN       NaN

In [177]:
print(len(set(zip(price_monitoring.PL,price_monitoring.SKU)) & set(zip(promotion.PL,promotion.SKU))))

54

In [178]:
price_monitoring[price_monitoring['SEASON'].notna()][
    ['SKU','PL','SEASON','PROMOTION']
].head(10)

         SKU               PL SEASON           PROMOTION
12   81B19PA   HP81_PC_Laptop     Q4            15 % off
25   3YM22AA     HP3Y_SUP_INK     Q4        20% off  ink
40   8L146PA   HP8L_PC_Laptop     Q4            15 % off
42    CF501A     HPCF_SUP_TON     Q4        20% off  ink
71    381U0A       HP38_PH_LJ     Q4  $10 off laser jet
75   CN047AA     HPCN_SUP_INK     Q4        20% off  ink
86    Z7Y82A     HPZ7_SUP_TON     Q4        20% off  ink
103   CN636A     HPCN_SUP_INK     Q4        20% off  ink
121   CF502A     HPCF_SUP_TON     Q4        20% off  ink
143  385Z7PA  HP38_PC_Desktop     Q4            15 % off

In [179]:
import re

price_monitoring['Promotional_price'] = price_monitoring['MAP_Price']

m = price_monitoring['PROMOTION'].str.extract(r'(\d+(?:\.\d+)?)\s*%')[0].astype(float)

price_monitoring.loc[m.notna(), 'Promotional_price'] = (
    price_monitoring.loc[m.notna(), 'MAP_Price'] * (1 - m[m.notna()] / 100)
)

C:\Users\HP\AppData\Local\Temp\ipykernel_17756\3615163273.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 73379.65   3151.2  197662.4    6839.2    2966.4    4848.     7701.6
   6489.6   42811.1    4568.     7084.8    2228.8   41117.9  173697.5
   3944.     4568.     5513.6   11211.2     375.2   42811.1    5494.4
   1404.     1947.2   11211.2   11211.2    4848.     5997.6    2966.4
  11491.2    2804.8    1663.2    1846.4   90906.65   7701.6   57241.55
  52509.6    3944.     1663.2    5513.6   71526.65   5494.4     864.
   3944.    42811.1  173697.5   90906.65 136067.15   7701.6    2314.4
  71909.15   7701.6   11211.2   65814.65   2314.4    5494.4   73379.65
   6030.4    5513.6    2314.4  281642.4   73379.65   8567.2    2314.4
   2409.6    2966.4   11491.2   34356.15  71526.65   2804.8    2966.4
   3151.2  173697.5    1982.4    6839.2    1982.4    3346.4    6030.4
 136067.15  34356.15   1947.2    3346.4   11211.2  197662.4  203489.15
   2409.6    5997.6   57241.55   2409.6   11211.2   71526.65   6923.2
   1846.4    6923.2    7084.8    5513.6  197662.4  281642.4    1663.2
   1404.    51530.4  203489.15   1663.2    4848.    52509.6    7701.6
  11211.2   32679.95   1846.4    3151.2   90906.65  71526.65  10607.15
    375.2    2409.6   52509.6   57241.55   1663.2    5696.     2409.6
   1846.4    1947.2    1404.     4568.      375.2   67727.15    375.2
   8567.2   90906.65 203489.15   4568.     1663.2     864.     4568.
   6923.2    1663.2    2804.8  173697.5    7701.6    2228.8    1982.4
   6839.2    6030.4    3346.4   65814.65   1846.4   73379.65   1982.4
   2314.4    3944.     6839.2    1404.     4630.4    8567.2    3151.2
   3346.4     375.2    4011.2   65814.65 281642.4   90906.65  34356.15
   6489.6    5513.6    5997.6    4568.    42811.1    2966.4   34356.15
   3151.2   73379.65   2409.6   10607.15  73379.65   1947.2   34356.15
   5513.6    2228.8   32679.95    375.2  136067.15   2314.4    6839.2
   7084.8   65814.65   2314.4   51530.4    1404.    10607.15   5513.6
   1663.2  197662.4   42811.1  197662.4    2228.8   71526.65 203489.15
 203489.15 281642.4     375.2    5997.6    5494.4    2228.8  281642.4
   7084.8   65814.65   4011.2   71909.15  42811.1    4011.2    8567.2
   7701.6   65814.65   2314.4    5696.     4630.4    6839.2    4630.4
  11491.2    6030.4    8567.2    5696.     2228.8   52509.6   41117.9
  90906.65  57241.55   1663.2     864.     5494.4   51530.4    8567.2
  10607.15   1947.2   67727.15   2966.4  136067.15  52509.6    2314.4
  52509.6    4568.    73379.65   6839.2    1947.2    6489.6    6489.6
 281642.4    5696.     8567.2  281642.4    3944.     1947.2    2966.4
  65814.65   7701.6   11491.2    1663.2    4848.      375.2   41117.9
   1846.4    7084.8   71526.65   6923.2    4011.2   32679.95  71909.15
    375.2   42811.1    2409.6    6030.4   10607.15  52509.6   52509.6
 136067.15   5997.6    6030.4    1846.4     375.2    1846.4   51530.4
  41117.9  203489.15   6923.2    6489.6   52509.6   67727.15 173697.5
 173697.5    4011.2    3944.     2228.8    5513.6   11491.2    1404.
   5494.4   42811.1    8567.2   71526.65   5513.6    5513.6    7084.8
   3346.4  197662.4     864.    11211.2     375.2    1404.     6030.4
   7701.6    6030.4   32679.95   3944.      375.2   51530.4   52509.6
  67727.15   7084.8    5494.4   34356.15 197662.4    4568.   136067.15
   4011.2    6839.2    3151.2    5997.6  203489.15    375.2   65814.65
   5997.6    4011.2   11211.2   32679.95 281642.4   67727.15  11211.2
  90906.65  90906.65  34356.15  34356.15  41117.9   71909.15    864.
   2804.8   41117.9    3944.   281642.4   67727.15  10607.15 281642.4
 197662.4  197662.4  173697.5   11491.2  173697.5    3151.2    5513.6
   3346.4    6923.2   32679.95  57241.55   4848.    65814.65   5696.
  51530.4     375.2   32679.95   1404.   136067.15   2966.4    3944.
   4630.4   32679.95   4011.2    4848.    57241.55   3346.4  173697.5
   2966.4    3944.     3151.2  281642.4   32679.95   5696.     6839.2
   6489.6     375.2    5696.    32679.95   4630.4   90906.65  71909.15
   1947.2    2804.8    3151.2   51530.4    2228.8   32679.95   6839.2
   5696.     2314.4    4568.    71526.65   7084.8    7701.6    4848.
 136067.15   6489.6    7084.8   32679.95  11491.2    2966.4    8567.2
  90906.65  11491.2    2409.6   51530.4   73379.65 197662.4   52509.6
   2228.8    2804.8    6839.2  173697.5   32679.95 281642.4    6030.4
   8567.2   41117.9     864.    41117.9  197662.4   11491.2    2228.8
   3151.2   11211.2  281642.4    5494.4    6030.4    7084.8    7084.8
   1947.2    6489.6    2409.6    2314.4    1663.2    6839.2    4568.
   2228.8    7701.6  173697.5     864.     2804.8  173697.5    1404.
   2228.8    4630.4   11211.2    5494.4    1404.   281642.4    5997.6
   3346.4    4568.     2228.8    5696.    73379.65  52509.6   57241.55
   1404.    57241.55   7701.6    7084.8  281642.4    3346.4   65814.65
  90906.65   5696.     1404.     5513.6  203489.15   2966.4    3944.
 136067.15   1982.4    7084.8    1404.     8567.2  203489.15  42811.1
   6030.4    7701.6    6489.6   71526.65   6030.4   34356.15   3151.2
   4568.    41117.9    2409.6   90906.65  11491.2    1982.4    1404.
   4630.4   34356.15   4630.4    5494.4    4011.2   11491.2   52509.6
   1982.4    1663.2   10607.15   5513.6   65814.65  51530.4   11491.2
   5696.    51530.4    1846.4  281642.4    6923.2    2804.8    3151.2
  34356.15  42811.1    4568.     5513.6   67727.15  42811.1   10607.15
   3944.     6923.2    1982.4    5696.    11491.2   34356.15 281642.4
 203489.15  90906.65   1947.2     375.2    6839.2  203489.15   2409.6
   5997.6  136067.15   6489.6    7701.6    4011.2    4630.4    2228.8
   5997.6   32679.95   2804.8    5696.     2314.4    8567.2    6030.4
   4630.4    4011.2     864.    71526.65   5997.6    2314.4   42811.1
 197662.4    2966.4   52509.6    4848.     4848.     6489.6    4568.
   8567.2   42811.1    6489.6   73379.65  73379.65  51530.4    2314.4
 136067.15   1947.2   57241.55  11211.2   73379.65 136067.15   4568.
   5696.    67727.15   2966.4    5494.4   71909.15   1404.     4848.
  71909.15  32679.95   2804.8    4011.2    5494.4   52509.6   57241.55]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  price_monitoring.loc[m.notna(), 'Promotional_price'] = (

In [180]:
price_monitoring[
    price_monitoring['PROMOTION'].notna()
][['SKU','MAP_Price','SEASON','PROMOTION','Promotional_price']].head(10)

         SKU  MAP_Price SEASON           PROMOTION  Promotional_price
12   81B19PA      86329     Q4            15 % off           73379.65
25   3YM22AA       3939     Q4        20% off  ink            3151.20
40   8L146PA     232544     Q4            15 % off          197662.40
42    CF501A       8549     Q4        20% off  ink            6839.20
71    381U0A      18899     Q4  $10 off laser jet            18899.00
75   CN047AA       3708     Q4        20% off  ink            2966.40
86    Z7Y82A       6060     Q4        20% off  ink            4848.00
103   CN636A       9627     Q4        20% off  ink            7701.60
121   CF502A       8112     Q4        20% off  ink            6489.60
143  385Z7PA      50366     Q4            15 % off           42811.10

In [181]:
cols = ['SKU','Violation_date','PL','Category','Sub_category','Region',
        'Marketplace','Seller_name','MAP_Price','LPP','Advertised_price',
        'Season','Promotional_price']

price_monitoring = price_monitoring[cols]
price_monitoring.head()

,SKU,Violation_date,PL,Category,Sub_category,Region,Marketplace,Seller_name,MAP_Price,LPP,Advertised_price,Season,Promotional_price
0,6X3W4PA,2026-10-03,HP6X_PC_Desktop,PC,Desktop,USA,Flipkart,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),33369,30332.421,460.440,NaN,33369.0
1,81H48PA,2026-10-03,HP81_PC_Laptop,PC,Laptop,USA,Flipkart,SHOP 24/7,73919,71405.754,940.200,NaN,73919.0
2,676M7A,2026-10-03,HP67_SUP_INK,SUP,INK,UAE,eBay,OPSUZY,13461,12586.035,651.640,NaN,13461.0
3,CF361A,2026-10-03,HPCF_SUP_TON,SUP,TON,UK,eBay,Abbey Edge,19396,17630.964,202.382,NaN,19396.0
4,P2V25A,2026-10-03,HPP2_SUP_INK,SUP,INK,UAE,Snapdeal,ASTraders,7752,7248.120,368.280,NaN,7752.0

In [188]:
price_monitoring

,SKU,Violation_date,PL,Category,Sub_category,Region,Marketplace,Seller_name,MAP_Price,LPP,Advertised_price,Season,Promotional_price
0,6X3W4PA,2026-10-03,HP6X_PC_Desktop,PC,Desktop,USA,Flipkart,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),33369,30332.421,460.440,NaN,33369.0
1,81H48PA,2026-10-03,HP81_PC_Laptop,PC,Laptop,USA,Flipkart,SHOP 24/7,73919,71405.754,940.200,NaN,73919.0
2,676M7A,2026-10-03,HP67_SUP_INK,SUP,INK,UAE,eBay,OPSUZY,13461,12586.035,651.640,NaN,13461.0
3,CF361A,2026-10-03,HPCF_SUP_TON,SUP,TON,UK,eBay,Abbey Edge,19396,17630.964,202.382,NaN,19396.0
4,P2V25A,2026-10-03,HPP2_SUP_INK,SUP,INK,UAE,Snapdeal,ASTraders,7752,7248.120,368.280,NaN,7752.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9656,2W953PA,2026-10-03,HP2W_PC_Desktop,PC,Desktop,UK,Amazon,ELEMENT ENTERPRISES,41157,37411.713,429.392,NaN,41157.0
9657,8F6C4PA,2026-10-03,HP8F_PC_Laptop,PC,Laptop,UAE,Amazon,Vidya Books A'bad,160379,154926.114,7762.480,NaN,160379.0
9658,9U2C4PA,2026-10-03,HP9U_PC_Laptop,PC,Laptop,IND,Amazon,HIRVAX,142099,137267.634,152050.000,NaN,142099.0
9659,8Q3X5PA,2026-10-03,HP8Q_PC_Laptop,PC,Laptop,USA,eBay,SAM ENTERPRISE COLLECTION,46324,44748.984,378.000,NaN,46324.0
9660,8L147PA,2026-10-03,HP8L_PC_Laptop,PC,Laptop,CAN,Amazon,ASTITA,272087,262836.042,4832.320,NaN,272087.0

In [189]:
price_monitoring['Season'] = 'Q4'

In [190]:
price_monitoring[['SKU','PL','Season','Promotional_price']].head()

       SKU               PL Season  Promotional_price
0  6X3W4PA  HP6X_PC_Desktop     Q4            33369.0
1  81H48PA   HP81_PC_Laptop     Q4            73919.0
2   676M7A     HP67_SUP_INK     Q4            13461.0
3   CF361A     HPCF_SUP_TON     Q4            19396.0
4   P2V25A     HPP2_SUP_INK     Q4             7752.0

### merge columns

In [191]:
price_monitoring = price_monitoring.merge(
    promotion[['PL','SKU','PROMOTION']],
    on=['PL','SKU'],
    how='left'
)

### calculate to the promotional price

In [192]:
price_monitoring['Promotional_price'] = price_monitoring['MAP_Price']

price_monitoring.loc[price_monitoring['PROMOTION'].str.contains('20% off', na=False),
                      'Promotional_price'] *= 0.80

price_monitoring.loc[price_monitoring['PROMOTION'].str.contains('15 % off|15% off', na=False),
                      'Promotional_price'] *= 0.85

C:\Users\HP\AppData\Local\Temp\ipykernel_17756\4242813566.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 3151.2  6839.2  2966.4  4848.   7701.6  6489.6  4568.   7084.8  2228.8
  3944.   4568.   5513.6 11211.2   375.2  5494.4  1404.   1947.2 11211.2
 11211.2  4848.   5997.6  2966.4 11491.2  2804.8  1663.2  1846.4  7701.6
  3944.   1663.2  5513.6  5494.4   864.   3944.   7701.6  2314.4  7701.6
 11211.2  2314.4  5494.4  6030.4  5513.6  2314.4  8567.2  2314.4  2409.6
  2966.4 11491.2  2804.8  2966.4  3151.2  1982.4  6839.2  1982.4  3346.4
  6030.4  1947.2  3346.4 11211.2  2409.6  5997.6  2409.6 11211.2  6923.2
  1846.4  6923.2  7084.8  5513.6  1663.2  1404.   1663.2  4848.   7701.6
 11211.2  1846.4  3151.2   375.2  2409.6  1663.2  5696.   2409.6  1846.4
  1947.2  1404.   4568.    375.2   375.2  8567.2  4568.   1663.2   864.
  4568.   6923.2  1663.2  2804.8  7701.6  2228.8  1982.4  6839.2  6030.4
  3346.4  1846.4  1982.4  2314.4  3944.   6839.2  1404.   4630.4  8567.2
  3151.2  3346.4   375.2  4011.2  6489.6  5513.6  5997.6  4568.   2966.4
  3151.2  2409.6  1947.2  5513.6  2228.8   375.2  2314.4  6839.2  7084.8
  2314.4  1404.   5513.6  1663.2  2228.8   375.2  5997.6  5494.4  2228.8
  7084.8  4011.2  4011.2  8567.2  7701.6  2314.4  5696.   4630.4  6839.2
  4630.4 11491.2  6030.4  8567.2  5696.   2228.8  1663.2   864.   5494.4
  8567.2  1947.2  2966.4  2314.4  4568.   6839.2  1947.2  6489.6  6489.6
  5696.   8567.2  3944.   1947.2  2966.4  7701.6 11491.2  1663.2  4848.
   375.2  1846.4  7084.8  6923.2  4011.2   375.2  2409.6  6030.4  5997.6
  6030.4  1846.4   375.2  1846.4  6923.2  6489.6  4011.2  3944.   2228.8
  5513.6 11491.2  1404.   5494.4  8567.2  5513.6  5513.6  7084.8  3346.4
   864.  11211.2   375.2  1404.   6030.4  7701.6  6030.4  3944.    375.2
  7084.8  5494.4  4568.   4011.2  6839.2  3151.2  5997.6   375.2  5997.6
  4011.2 11211.2 11211.2   864.   2804.8  3944.  11491.2  3151.2  5513.6
  3346.4  6923.2  4848.   5696.    375.2  1404.   2966.4  3944.   4630.4
  4011.2  4848.   3346.4  2966.4  3944.   3151.2  5696.   6839.2  6489.6
   375.2  5696.   4630.4  1947.2  2804.8  3151.2  2228.8  6839.2  5696.
  2314.4  4568.   7084.8  7701.6  4848.   6489.6  7084.8 11491.2  2966.4
  8567.2 11491.2  2409.6  2228.8  2804.8  6839.2  6030.4  8567.2   864.
 11491.2  2228.8  3151.2 11211.2  5494.4  6030.4  7084.8  7084.8  1947.2
  6489.6  2409.6  2314.4  1663.2  6839.2  4568.   2228.8  7701.6   864.
  2804.8  1404.   2228.8  4630.4 11211.2  5494.4  1404.   5997.6  3346.4
  4568.   2228.8  5696.   1404.   7701.6  7084.8  3346.4  5696.   1404.
  5513.6  2966.4  3944.   1982.4  7084.8  1404.   8567.2  6030.4  7701.6
  6489.6  6030.4  3151.2  4568.   2409.6 11491.2  1982.4  1404.   4630.4
  4630.4  5494.4  4011.2 11491.2  1982.4  1663.2  5513.6 11491.2  5696.
  1846.4  6923.2  2804.8  3151.2  4568.   5513.6  3944.   6923.2  1982.4
  5696.  11491.2  1947.2   375.2  6839.2  2409.6  5997.6  6489.6  7701.6
  4011.2  4630.4  2228.8  5997.6  2804.8  5696.   2314.4  8567.2  6030.4
  4630.4  4011.2   864.   5997.6  2314.4  2966.4  4848.   4848.   6489.6
  4568.   8567.2  6489.6  2314.4  1947.2 11211.2  4568.   5696.   2966.4
  5494.4  1404.   4848.   2804.8  4011.2  5494.4]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  price_monitoring.loc[price_monitoring['PROMOTION'].str.contains('20% off', na=False),

In [193]:
# Final column order
cols = ['SKU','Violation_date','PL','Category','Sub_category','Region',
        'Marketplace','Seller_name','MAP_Price','LPP','Advertised_price',
        'Season','Promotional_price']

price_monitoring = price_monitoring[cols]
price_monitoring.head()

,SKU,Violation_date,PL,Category,Sub_category,Region,Marketplace,Seller_name,MAP_Price,LPP,Advertised_price,Season,Promotional_price
0,6X3W4PA,2026-10-03,HP6X_PC_Desktop,PC,Desktop,USA,Flipkart,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),33369,30332.421,460.440,Q4,33369.0
1,81H48PA,2026-10-03,HP81_PC_Laptop,PC,Laptop,USA,Flipkart,SHOP 24/7,73919,71405.754,940.200,Q4,73919.0
2,676M7A,2026-10-03,HP67_SUP_INK,SUP,INK,UAE,eBay,OPSUZY,13461,12586.035,651.640,Q4,13461.0
3,CF361A,2026-10-03,HPCF_SUP_TON,SUP,TON,UK,eBay,Abbey Edge,19396,17630.964,202.382,Q4,19396.0
4,P2V25A,2026-10-03,HPP2_SUP_INK,SUP,INK,UAE,Snapdeal,ASTraders,7752,7248.120,368.280,Q4,7752.0

In [194]:
price_monitoring.shape

(9661, 13)

In [195]:
price_monitoring.to_excel("price_monitoring_table.xlsx", index=False)

In [197]:
price_monitoring.isna().sum()

SKU                  0
Violation_date       0
PL                   0
Category             0
Sub_category         0
Region               0
Marketplace          0
Seller_name          0
MAP_Price            0
LPP                  0
Advertised_price     0
Season               0
Promotional_price    0
dtype: int64

In [198]:
# Q4 promotion + promotional price
price_monitoring = price_monitoring.merge(
    promotion[['PL','SKU','PROMOTION']],
    on=['PL','SKU'], how='left'
)

price_monitoring['Season'] = 'Q4'
price_monitoring['Promotional_price'] = price_monitoring['MAP_Price'].astype(float)

price_monitoring.loc[price_monitoring['PROMOTION'].str.contains('20% off', na=False),
                     'Promotional_price'] *= 0.80
price_monitoring.loc[price_monitoring['PROMOTION'].str.contains('15 ?% off', na=False),
                     'Promotional_price'] *= 0.85

# Final column order
cols = ['SKU','Violation_date','PL','Category','Sub_category','Region',
        'Marketplace','Seller_name','MAP_Price','LPP','Advertised_price',
        'Season','Promotional_price']

price_monitoring = price_monitoring[cols]
price_monitoring.head()

,SKU,Violation_date,PL,Category,Sub_category,Region,Marketplace,Seller_name,MAP_Price,LPP,Advertised_price,Season,Promotional_price
0,6X3W4PA,2026-10-03,HP6X_PC_Desktop,PC,Desktop,USA,Flipkart,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),33369,30332.421,460.440,Q4,33369.0
1,81H48PA,2026-10-03,HP81_PC_Laptop,PC,Laptop,USA,Flipkart,SHOP 24/7,73919,71405.754,940.200,Q4,73919.0
2,676M7A,2026-10-03,HP67_SUP_INK,SUP,INK,UAE,eBay,OPSUZY,13461,12586.035,651.640,Q4,13461.0
3,CF361A,2026-10-03,HPCF_SUP_TON,SUP,TON,UK,eBay,Abbey Edge,19396,17630.964,202.382,Q4,19396.0
4,P2V25A,2026-10-03,HPP2_SUP_INK,SUP,INK,UAE,Snapdeal,ASTraders,7752,7248.120,368.280,Q4,7752.0

In [199]:
price_monitoring.isna().sum()

SKU                  0
Violation_date       0
PL                   0
Category             0
Sub_category         0
Region               0
Marketplace          0
Seller_name          0
MAP_Price            0
LPP                  0
Advertised_price     0
Season               0
Promotional_price    0
dtype: int64

In [200]:
price_monitoring.to_sql(
    'price_monitoring_table',
    con=engine,
    if_exists='replace',
    index=False
)

9661

### creating to the voilation_table.

In [3]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (2.0.54)
Requirement already satisfied: pymysql in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (1.2.3)
Requirement already satisfied: greenlet>=1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [5]:
engine = create_engine(
    "mysql+pymysql://root:srikutty001@localhost:3306/data_analysis"
)

In [6]:
pd.read_sql("SHOW TABLES", engine)

  Tables_in_data_analysis
0  category_mapping_table
1                pl_table
2        price_list_table
3  price_monitoring_table
4         promotion_table
5    seller_mapping_table
6               sku_table

In [7]:
price_monitoring = pd.read_sql(
    "SELECT * FROM price_monitoring_table",
    engine
)

price_monitoring.head()

,SKU,Violation_date,PL,Category,Sub_category,Region,Marketplace,Seller_name,MAP_Price,LPP,Advertised_price,Season,Promotional_price
0,6X3W4PA,2026-10-03,HP6X_PC_Desktop,PC,Desktop,USA,Flipkart,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),33369,30332.421,460.440,Q4,33369.0
1,81H48PA,2026-10-03,HP81_PC_Laptop,PC,Laptop,USA,Flipkart,SHOP 24/7,73919,71405.754,940.200,Q4,73919.0
2,676M7A,2026-10-03,HP67_SUP_INK,SUP,INK,UAE,eBay,OPSUZY,13461,12586.035,651.640,Q4,13461.0
3,CF361A,2026-10-03,HPCF_SUP_TON,SUP,TON,UK,eBay,Abbey Edge,19396,17630.964,202.382,Q4,19396.0
4,P2V25A,2026-10-03,HPP2_SUP_INK,SUP,INK,UAE,Snapdeal,ASTraders,7752,7248.120,368.280,Q4,7752.0

In [8]:
violation_table = price_monitoring[
    price_monitoring['Advertised_price'] < price_monitoring['Promotional_price']
].copy()

violation_table['Violation_count'] = (
    violation_table.groupby(['Seller_name','SKU']).cumcount() + 1
)

violation_table['Action'] = violation_table['Violation_count'].map({
    1: 'Warning 1 - Email',
    2: 'Warning 2 - Email',
    3: 'Terminate/Block Product'
}).fillna('Terminate/Block Product')

In [9]:
violation_table['Price_difference'] = (
    violation_table['Promotional_price'] -
    violation_table['Advertised_price']
)

In [10]:
violation_table = violation_table[
    ['SKU','Violation_date','PL','Category','Sub_category',
     'Region','Marketplace','Seller_name','MAP_Price','LPP',
     'Advertised_price','Season','Promotional_price',
     'Price_difference','Violation_count','Action']
]

In [11]:
violation_table.head()

,SKU,Violation_date,PL,Category,Sub_category,Region,Marketplace,Seller_name,MAP_Price,LPP,Advertised_price,Season,Promotional_price,Price_difference,Violation_count,Action
0,6X3W4PA,2026-10-03,HP6X_PC_Desktop,PC,Desktop,USA,Flipkart,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),33369,30332.421,460.440,Q4,33369.0,32908.560,1,Warning 1 - Email
1,81H48PA,2026-10-03,HP81_PC_Laptop,PC,Laptop,USA,Flipkart,SHOP 24/7,73919,71405.754,940.200,Q4,73919.0,72978.800,1,Warning 1 - Email
2,676M7A,2026-10-03,HP67_SUP_INK,SUP,INK,UAE,eBay,OPSUZY,13461,12586.035,651.640,Q4,13461.0,12809.360,1,Warning 1 - Email
3,CF361A,2026-10-03,HPCF_SUP_TON,SUP,TON,UK,eBay,Abbey Edge,19396,17630.964,202.382,Q4,19396.0,19193.618,1,Warning 1 - Email
4,P2V25A,2026-10-03,HPP2_SUP_INK,SUP,INK,UAE,Snapdeal,ASTraders,7752,7248.120,368.280,Q4,7752.0,7383.720,1,Warning 1 - Email

In [12]:
violation_table[['SKU','Seller_name','Violation_count','Action']].head(20)

,SKU,Seller_name,Violation_count,Action
0,6X3W4PA,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),1,Warning 1 - Email
1,81H48PA,SHOP 24/7,1,Warning 1 - Email
2,676M7A,OPSUZY,1,Warning 1 - Email
3,CF361A,Abbey Edge,1,Warning 1 - Email
4,P2V25A,ASTraders,1,Warning 1 - Email
5,3WX30A,EASYSHOP ENTERPRISES,1,Warning 1 - Email
6,64X69AA,E Basket-,1,Warning 1 - Email
7,9U7H2PA,AARSH LIFESTYLE,1,Warning 1 - Email
9,Z7Y79A,Techsaaz Solutions LLP,1,Warning 1 - Email
10,64V81AA,Opus_Retail,1,Warning 1 - Email
11,3JA77AA,Avenue Overseas Private Limited,1,Warning 1 - Email
12,81B19PA,Yellow Weaves,1,Warning 1 - Email
15,C2P20AA,Yaarideal,1,Warning 1 - Email
16,CE742A,USA ORIGINALS (Authorized Distributor ),1,Warning 1 - Email
17,53P41A,SNOWBIRD®,1,Warning 1 - Email
18,CF362A,VARNITYA®,1,Warning 1 - Email
20,7K1H4PA,Alvero®,1,Warning 1 - Email
21,W2043A,Aggarwal_Store,1,Warning 1 - Email
22,Z7Y81A,Shri Ganeshji Sales,1,Warning 1 - Email
23,W2311A,CIRCUIT ZONE-AMROLI,1,Warning 1 - Email

In [13]:
violation_table.to_excel("violation_table.xlsx", index=False)

In [14]:
violation_table.to_sql(
    "violation_table",
    engine,
    if_exists="replace",
    index=False
)

7902

In [15]:
seller = pd.read_sql("SELECT SKU, Marketplace, Seller_name, Seller_Email FROM seller_mapping_table", engine)

violation_table = violation_table.merge(
    seller,
    on=['SKU','Marketplace','Seller_name'],
    how='left'
)

In [16]:
violation_table[['SKU','Seller_name','Seller_Email','Violation_count','Action']].head()

,SKU,Seller_name,Seller_Email,Violation_count,Action
0,6X3W4PA,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),None,1,Warning 1 - Email
1,81H48PA,SHOP 24/7,None,1,Warning 1 - Email
2,676M7A,OPSUZY,None,1,Warning 1 - Email
3,CF361A,Abbey Edge,None,1,Warning 1 - Email
4,P2V25A,ASTraders,None,1,Warning 1 - Email

In [17]:
violation = pd.read_sql("SELECT * FROM violation_table", engine)

In [18]:
seller = pd.read_sql(
    "SELECT SKU, Marketplace, Seller_name, Seller_Email FROM seller_mapping_table",
    engine
)

violation = violation.merge(
    seller,
    on=['SKU', 'Marketplace', 'Seller_name'],
    how='left'
)

In [19]:
violation[['SKU','Seller_name','Seller_Email','Violation_count','Action']].head()

,SKU,Seller_name,Seller_Email,Violation_count,Action
0,6X3W4PA,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),None,1,Warning 1 - Email
1,81H48PA,SHOP 24/7,None,1,Warning 1 - Email
2,676M7A,OPSUZY,None,1,Warning 1 - Email
3,CF361A,Abbey Edge,None,1,Warning 1 - Email
4,P2V25A,ASTraders,None,1,Warning 1 - Email

In [21]:
!pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
     ---------------------------------------- 0.0/253.0 kB ? eta -:--:--
     - -------------------------------------- 10.2/253.0 kB ? eta -:--:--
     ------------ -------------------------- 81.9/253.0 kB 1.6 MB/s eta 0:00:01
     -------------------------- ----------- 174.1/253.0 kB 2.1 MB/s eta 0:00:01
     ------------------------------------ - 245.8/253.0 kB 2.2 MB/s eta 0:00:01
     -------------------------------------- 253.0/253.0 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: lxml>=3.1.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from python-docx) (6.1.3)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from python-docx) (4.15.0)
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
from docx import Document

template = "Violation_Email.docx"

def create_letter(row):
    doc = Document(template)

    for p in doc.paragraphs:
        for key, value in row.items():
            p.text = p.text.replace("{" + key + "}", str(value))

    for table in doc.tables:
        for cell in table._cells:
            for key, value in row.items():
                cell.text = cell.text.replace("{" + key + "}", str(value))

    file = f"Violation_{row['SKU']}_{row['Violation_count']}.docx"
    doc.save(file)
    return file

In [24]:
row = violation.iloc[0]

letter = create_letter(row)

print(letter)

Violation_6X3W4PA_1.docx

### gmail sending code.

In [39]:
import smtplib
from email.message import EmailMessage

In [45]:
with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
    server.login(EMAIL, APP_PASSWORD)

SMTPServerDisconnected: Connection unexpectedly closed

In [40]:
EMAIL = "srikutty709451@gmail.com"
APP_PASSWORD = "srikutty001*"

In [41]:
def send_email(row, attachment):

    msg = EmailMessage()

    msg["From"] = EMAIL
    msg["To"] = row["Seller_Email"]
    msg["Subject"] = f"Price Violation Notice - {row['SKU']}"

    msg.set_content(
        f"""Dear {row['Seller_name']},

A pricing violation has been identified.

SKU: {row['SKU']}
Marketplace: {row['Marketplace']}
Violation Count: {row['Violation_count']}
Action: {row['Action']}

Please take the necessary corrective action immediately.

Regards,
LPP / MAP Monitoring Team"""
    )

    with open(attachment, "rb") as f:
        msg.add_attachment(
            f.read(),
            maintype="application",
            subtype="vnd.openxmlformats-officedocument.wordprocessingml.document",
            filename=attachment
        )

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(EMAIL, APP_PASSWORD)
        server.send_message(msg)

In [53]:
import socket

s = socket.create_connection(("smtp.gmail.com", 587), timeout=10)
print("SMTP server reachable")
s.close()

SMTP server reachable

In [54]:
import smtplib

server = smtplib.SMTP("smtp.gmail.com", 587, timeout=30)
server.ehlo()
server.starttls()
server.ehlo()
print("SMTP login screen ready")
server.quit()

SMTP login screen ready

(221,
 b'2.0.0 closing connection 5a478bee46e88-351272bb9basm2363013eec.24 - gsmtp')

In [ ]:
# tnxi usfi tehw czma

In [ ]:
# fdei tnme omqo tyjp

In [70]:
import getpass

EMAIL = input("Gmail: ")
APP_PASSWORD = getpass.getpass("App Password: ")

Gmail:  srikutty709451@gmail.com
App Password:  ········

In [71]:
EMAIL = EMAIL.strip()
APP_PASSWORD = APP_PASSWORD.replace(" ", "").strip()

print(len(APP_PASSWORD))

16

In [72]:
import smtplib

server = smtplib.SMTP("smtp.gmail.com", 587, timeout=30)
server.starttls()
server.login(EMAIL, APP_PASSWORD)

print("LOGIN SUCCESS")
server.quit()

LOGIN SUCCESS

(221,
 b'2.0.0 closing connection a92af1059eb24-151fc87346bsm23163774c88.8 - gsmtp')

In [84]:
import smtplib
from email.message import EmailMessage

In [77]:
print(row["Seller_Email"])

None

In [78]:
print(violation.columns.tolist())

['SKU', 'Violation_date', 'PL', 'Category', 'Sub_category', 'Region', 'Marketplace', 'Seller_name', 'MAP_Price', 'LPP', 'Advertised_price', 'Season', 'Promotional_price', 'Price_difference', 'Violation_count', 'Action', 'Seller_Email']

In [82]:
def send_email(row, attachment):
    msg = EmailMessage()

    msg["From"] = EMAIL
    msg["To"] = EMAIL
    msg["Subject"] = f"Price Violation Notice - {row['SKU']}"

    msg.set_content(
        f"""Dear Team,

A pricing violation has been identified.

SKU: {row['SKU']}
Marketplace: {row['Marketplace']}
Violation Count: {row['Violation_count']}
Action: {row['Action']}

Please take the necessary corrective action.

Regards,
MAP Monitoring Team"""
    )

    with open(attachment, "rb") as f:
        msg.add_attachment(
            f.read(),
            maintype="application",
            subtype="vnd.openxmlformats-officedocument.wordprocessingml.document",
            filename=attachment
        )

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(EMAIL, APP_PASSWORD)
        server.send_message(msg)

    print("Email sent successfully")

In [83]:
row = violation.iloc[0]

letter = create_letter(row)

send_email(row, letter)

Email sent successfully

In [87]:
seller_email = violation[['Seller_name']].drop_duplicates()
seller_email['Seller_Email'] = ''

seller_email.to_excel("SELLER_EMAIL_MAPPING.xlsx", index=False)

seller_email.head()

                                         Seller_name Seller_Email
0  H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction )
1                                          SHOP 24/7
2                                             OPSUZY
3                                         Abbey Edge
4                                          ASTraders

In [88]:
seller_email = pd.read_excel("SELLER_EMAIL_MAPPING.xlsx")

In [89]:
seller_email.head()

                                         Seller_name  Seller_Email
0  H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction )           NaN
1                                          SHOP 24/7           NaN
2                                             OPSUZY           NaN
3                                         Abbey Edge           NaN
4                                          ASTraders           NaN

In [91]:
violation = violation.drop(columns='Seller_Email')

violation = violation.merge(
    seller_email,
    on='Seller_name',
    how='left'
)

In [92]:
violation[['Seller_name', 'Seller_Email']].head()

                                         Seller_name  Seller_Email
0  H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction )           NaN
1                                          SHOP 24/7           NaN
2                                             OPSUZY           NaN
3                                         Abbey Edge           NaN
4                                          ASTraders           NaN

In [94]:
seller_email = pd.read_excel("SELLER_EMAIL_MAPPING.xlsx")

In [95]:
violation = violation.drop(columns="Seller_Email")

violation = violation.merge(
    seller_email,
    on="Seller_name",
    how="left"
)

In [96]:
violation[["Seller_name", "Seller_Email"]].head()

                                         Seller_name  Seller_Email
0  H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction )           NaN
1                                          SHOP 24/7           NaN
2                                             OPSUZY           NaN
3                                         Abbey Edge           NaN
4                                          ASTraders           NaN

In [98]:
seller_email = violation[['Seller_name']].drop_duplicates()
seller_email['Seller_Email'] = EMAIL

In [99]:
seller_email.head()

                                         Seller_name              Seller_Email
0  H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction )  srikutty709451@gmail.com
1                                          SHOP 24/7  srikutty709451@gmail.com
2                                             OPSUZY  srikutty709451@gmail.com
3                                         Abbey Edge  srikutty709451@gmail.com
4                                          ASTraders  srikutty709451@gmail.com

In [100]:
violation = violation.drop(columns='Seller_Email')

violation = violation.merge(
    seller_email,
    on='Seller_name',
    how='left'
)

In [101]:
violation[['Seller_name','Seller_Email']].head()

                                         Seller_name              Seller_Email
0  H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction )  srikutty709451@gmail.com
1                                          SHOP 24/7  srikutty709451@gmail.com
2                                             OPSUZY  srikutty709451@gmail.com
3                                         Abbey Edge  srikutty709451@gmail.com
4                                          ASTraders  srikutty709451@gmail.com

In [102]:
row = violation.iloc[0]

letter = create_letter(row)
send_email(row, letter)

Email sent successfully

### 10 demo send voilation email.

In [103]:
demo = violation.head(10).copy()
demo["Seller_Email"] = EMAIL

In [104]:
for _, row in demo.iterrows():
    letter = create_letter(row)
    send_email(row, letter)

Email sent successfully
Email sent successfully
Email sent successfully
Email sent successfully
Email sent successfully
Email sent successfully
Email sent successfully
Email sent successfully
Email sent successfully
Email sent successfully

In [105]:
demo[[
    "SKU",
    "Seller_name",
    "Advertised_price",
    "Promotional_price",
    "Violation_count",
    "Action"
]]

,SKU,Seller_name,Advertised_price,Promotional_price,Violation_count,Action
0,6X3W4PA,H.R.&COMPANY INDIA-LIMESHOT™ (100% Satisfaction ),460.440,33369.0,1,Warning 1 - Email
1,81H48PA,SHOP 24/7,940.200,73919.0,1,Warning 1 - Email
2,676M7A,OPSUZY,651.640,13461.0,1,Warning 1 - Email
3,CF361A,Abbey Edge,202.382,19396.0,1,Warning 1 - Email
4,P2V25A,ASTraders,368.280,7752.0,1,Warning 1 - Email
5,3WX30A,EASYSHOP ENTERPRISES,727.320,14890.0,1,Warning 1 - Email
6,64X69AA,E Basket-,74.448,13200.0,1,Warning 1 - Email
7,9U7H2PA,AARSH LIFESTYLE,1723.680,132999.0,1,Warning 1 - Email
8,Z7Y79A,Techsaaz Solutions LLP,146.828,14594.0,1,Warning 1 - Email
9,64V81AA,Opus_Retail,134.240,7629.0,1,Warning 1 - Email

In [106]:
violation.to_excel("Final_Violation_Report.xlsx", index=False)

In [107]:
violation.to_sql(
    "violation_table",
    con=engine,
    if_exists="replace",
    index=False
)

7902