# 1.install packages.

In [1]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4) (4.15.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Requirement already satisfied: beautifulsoup4 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from bs4) (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->bs4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->bs4) (4.15.0)
Installing collected packages: bs4
Successfully installed bs4-0.0.2

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!pip install requests

Requirement already satisfied: requests in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (2.34.2)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from requests) (2026.6.17)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.4.7)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
from sqlalchemy import create_engine

# 2.import laibraryes

In [5]:
from bs4 import BeautifulSoup
import requests,openpyxl

In [20]:
import pandas as pd
import re
import time

In [14]:
try:
    response=requests.get("https://www.flipkart.com/search?q=laptops&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off")
    soup=BeautifulSoup(response.text,'html.parser')
    # print(soup)
    # laptop_products=soup.find('body',class_="
    product_names = soup.find_all("div", class_="RGS5lk")
    print(product_names)
except Exception as e:
    print(e)

[]

In [15]:
print("Status:", response.status_code)
print("HTML length:", len(response.text))

Status: 200
HTML length: 190885

In [16]:
# Find all Flipkart product links

links = soup.find_all("a", href=True)

product_links = []

for link in links:
    href = link.get("href")
    
    if "/p/" in href:
        product_links.append("https://www.flipkart.com" + href.split("?")[0])

product_links = list(dict.fromkeys(product_links))

print("Product links found:", len(product_links))
print(*product_links[:10], sep="\n")

Product links found: 24
https://www.flipkart.com/lenovo-chromebook-11ijl9-intel-celeron-dual-core-n4500-4-gb-64-gb-emmc-storage-chrome-os/p/itmd2a376187074e
https://www.flipkart.com/lenovo-chromebook-mediatek-kompanio-520-4-gb-128-gb-emmc-storage-chrome-os-14m868/p/itm4dc67999fe3de
https://www.flipkart.com/acer-aspire-14-amd-ryzen-3-3200u-8-gb-256-gb-ssd-windows-11-home-as14-39-notebook/p/itmaaf97abbd3aef
https://www.flipkart.com/hp-mso-2024-intel-core-i3-13th-gen-1315u-16-gb-512-gb-ssd-windows-11-home-15-fd0574tu-15-fd0668tu-thin-light-laptop/p/itmcb9e5b7b2d3fb
https://www.flipkart.com/asus-chromebook-cx15-intel-celeron-dual-core-n50-4-gb-64-gb-emmc-storage-chrome-os-cx1505cta-s70256-laptop/p/itm987fe58d63593
https://www.flipkart.com/asus-expertbook-ultra-full-metal-nano-ceramic-coating-toled-touchscreen-copilot-intel-core-x7-358h-32-gb-1-tb-ssd-windows-11-home-b9406caa-th1205ws-thin-light-laptop/p/itm8f6006a76d8bf
https://www.flipkart.com/hp-omnibook-3-next-gen-ai-pc-snapdragon-x-8-gb-512-gb-ssd-windows-11-home-14-hz0056qu-laptop/p/itmfbff241a073bf
https://www.flipkart.com/primebook-2-pro-2026-in-built-ai-mediatek-helio-g99-mt8781-8-gb-128-gb-android-15-pbg9914128-4278c-laptop/p/itmdbf8db6a6f79a
https://www.flipkart.com/acer-aspire-3-i3-14th-gen-intel-core-100u-8-gb-512-gb-ssd-windows-11-home-a324-53-notebook/p/itmcc145dc1a3908
https://www.flipkart.com/acer-aspire-lite-metal-2026-amd-ryzen-3-quad-core-5400u-8-gb-256-gb-ssd-windows-11-home-al15-41-thin-light-laptop/p/itm1bc0bcb4598e7

In [17]:
print("Testing first product:")
print(product_links[0])

Testing first product:
https://www.flipkart.com/lenovo-chromebook-11ijl9-intel-celeron-dual-core-n4500-4-gb-64-gb-emmc-storage-chrome-os/p/itmd2a376187074e

In [18]:
product_url = product_links[0]

response = requests.get(product_url)

print("Status:", response.status_code)

product_soup = BeautifulSoup(response.text, "html.parser")

print("Page title:")
print(product_soup.title.get_text(strip=True))

Status: 200
Page title:
Lenovo Chromebook 11IJL9 Intel Celeron Dual Core N4500 - (4 GB/64 GB EMMC Storage/Chrome OS) Chromebook 11IJL9 Chromebook Rs.36502  Price in India - Buy Lenovo Chromebook 11IJL9 Intel Celeron Dual Core N4500 - (4 GB/64 GB EMMC Storage/Chrome OS) Chromebook 11IJL9 Chromebook Maca Blue Online - Lenovo : Flipkart.com

In [19]:
import re

title = product_soup.title.get_text(" ", strip=True)

# Product name
product_name = title.split(" Rs.")[0].strip()

# Selling price
price_match = re.search(r"Rs\.(\d[\d,]*)", title)

if price_match:
    selling_price = int(price_match.group(1).replace(",", ""))
else:
    selling_price = None

print("Product Name:", product_name)
print("Selling Price:", selling_price)
print("Product URL:", product_url)

Product Name: Lenovo Chromebook 11IJL9 Intel Celeron Dual Core N4500 - (4 GB/64 GB EMMC Storage/Chrome OS) Chromebook 11IJL9 Chromebook
Selling Price: 36502
Product URL: https://www.flipkart.com/lenovo-chromebook-11ijl9-intel-celeron-dual-core-n4500-4-gb-64-gb-emmc-storage-chrome-os/p/itmd2a376187074e

In [21]:


all_product_links = []

# Collect product links from multiple search pages
for page in range(1, 6):

    url = f"https://www.flipkart.com/search?q=laptops&page={page}"

    response = requests.get(url, headers={
        "User-Agent": "Mozilla/5.0"
    }, timeout=20)

    soup = BeautifulSoup(response.text, "html.parser")

    for link in soup.find_all("a", href=True):

        href = link.get("href")

        if href and "/p/" in href:
            full_url = "https://www.flipkart.com" + href.split("?")[0]

            if full_url not in all_product_links:
                all_product_links.append(full_url)

    print("Page", page, "links:", len(all_product_links))

    time.sleep(2)


# Keep only 100 products
all_product_links = all_product_links[:100]

print("Total products:", len(all_product_links))

Page 1 links: 24
Page 2 links: 42
Page 3 links: 61
Page 4 links: 75
Page 5 links: 93
Total products: 93

In [22]:
scraped_data = []

for i, product_url in enumerate(all_product_links, start=1):

    try:
        response = requests.get(
            product_url,
            headers={"User-Agent": "Mozilla/5.0"},
            timeout=20
        )

        product_soup = BeautifulSoup(response.text, "html.parser")
        title = product_soup.title.get_text(" ", strip=True)

        product_name = title.split(" Rs.")[0].strip()

        price_match = re.search(r"Rs\.(\d[\d,]*)", title)

        if price_match:
            selling_price = int(price_match.group(1).replace(",", ""))
        else:
            selling_price = None

        scraped_data.append({
            "Product_Name": product_name,
            "Product_URL": product_url,
            "Selling_Price": selling_price,
            "Platform": "Flipkart"
        })

        print(i, "/", len(all_product_links), "completed")

        time.sleep(2)

    except Exception as e:
        print("Error:", i, e)

print("New products scraped:", len(scraped_data))

1 / 93 completed
2 / 93 completed
3 / 93 completed
4 / 93 completed
5 / 93 completed
6 / 93 completed
7 / 93 completed
8 / 93 completed
9 / 93 completed
10 / 93 completed
11 / 93 completed
12 / 93 completed
13 / 93 completed
14 / 93 completed
15 / 93 completed
16 / 93 completed
17 / 93 completed
18 / 93 completed
19 / 93 completed
20 / 93 completed
21 / 93 completed
22 / 93 completed
23 / 93 completed
24 / 93 completed
25 / 93 completed
26 / 93 completed
27 / 93 completed
28 / 93 completed
29 / 93 completed
30 / 93 completed
31 / 93 completed
32 / 93 completed
33 / 93 completed
34 / 93 completed
35 / 93 completed
36 / 93 completed
37 / 93 completed
38 / 93 completed
39 / 93 completed
40 / 93 completed
41 / 93 completed
42 / 93 completed
43 / 93 completed
44 / 93 completed
45 / 93 completed
46 / 93 completed
47 / 93 completed
48 / 93 completed
49 / 93 completed
50 / 93 completed
51 / 93 completed
52 / 93 completed
53 / 93 completed
54 / 93 completed
55 / 93 completed
56 / 93 completed
57 / 93 completed
58 / 93 completed
59 / 93 completed
60 / 93 completed
61 / 93 completed
62 / 93 completed
63 / 93 completed
64 / 93 completed
65 / 93 completed
66 / 93 completed
67 / 93 completed
68 / 93 completed
69 / 93 completed
70 / 93 completed
71 / 93 completed
72 / 93 completed
73 / 93 completed
74 / 93 completed
75 / 93 completed
76 / 93 completed
77 / 93 completed
78 / 93 completed
79 / 93 completed
80 / 93 completed
81 / 93 completed
82 / 93 completed
83 / 93 completed
84 / 93 completed
85 / 93 completed
86 / 93 completed
87 / 93 completed
88 / 93 completed
89 / 93 completed
90 / 93 completed
91 / 93 completed
92 / 93 completed
93 / 93 completed
New products scraped: 93

In [23]:
new_df = pd.DataFrame(scraped_data)

new_df.head()

,Product_Name,Product_URL,Selling_Price,Platform
0,ASUS ExpertBook P1 with 1 Yr ADP (i3 14th Gen)...,https://www.flipkart.com/asus-expertbook-p1-1-...,109990,Flipkart
1,ASUS ExpertBook P1 with 1 Yr ADP (i3 14th Gen)...,https://www.flipkart.com/asus-expertbook-p1-1-...,99990,Flipkart
2,Acer Aspire 14 AMD Ryzen 3 3200U - (8 GB/256 G...,https://www.flipkart.com/acer-aspire-14-amd-ry...,79999,Flipkart
3,HP MSO 2024 Intel Core i3 13th Gen 1315U - (16...,https://www.flipkart.com/hp-mso-2024-intel-cor...,67990,Flipkart
4,ASUS Chromebook CX15 Intel Celeron Dual Core N...,https://www.flipkart.com/asus-chromebook-cx15-...,24990,Flipkart

In [27]:
old_df=pd.read_excel("flipkart_scraped_data.xlsx")
print("Old products:", len(old_df))
old_df.head()

Old products: 27

,Product_Name,Product_URL,Selling_Price
0,MOTOROLA pad 60 neo 8 GB RAM 128 GB ROM 11 inc...,https://www.flipkart.com/motorola-pad-60-neo-8...,43999
1,Acer Aspire 14 Office 2024 + M365 Basic (i5 14...,https://www.flipkart.com/a/p/itm1692bd8b2fe84?...,59990
2,Samsung Galaxy Book5 AI Metal Intel Core Ultra...,https://www.flipkart.com/a/p/itm1692bd8b2fe84?...,86990
3,Acer Aspire 7(i5 14th Gen) Intel Core 5 210H -...,https://www.flipkart.com/a/p/itm1692bd8b2fe84?...,104004
4,HP Omnibook X Flip Next Gen AI PC Intel Core U...,https://www.flipkart.com/a/p/itm1692bd8b2fe84?...,119990

In [28]:
old_7 = old_df.head(7).copy()

print("Old products selected:", len(old_7))

Old products selected: 7

In [29]:
final_df = pd.concat(
    [new_df, old_7],
    ignore_index=True
)

print("Final products:", len(final_df))

Final products: 100

In [30]:
final_df = final_df.drop_duplicates(
    subset=["Product_URL"]
).reset_index(drop=True)

print("Final unique products:", len(final_df))

Final unique products: 100

In [31]:
final_df.to_excel(
    "flipkart_100_products.xlsx",
    index=False
)

print("100-product Excel file created successfully!")

100-product Excel file created successfully!

In [35]:
# Read the scraped Excel file
df = pd.read_excel("flipkart_100_products.xlsx")

print("Rows:", len(df))
print(df.head())

Rows: 100
                                        Product_Name  \
0  ASUS ExpertBook P1 with 1 Yr ADP (i3 14th Gen)...
1  ASUS ExpertBook P1 with 1 Yr ADP (i3 14th Gen)...
2  Acer Aspire 14 AMD Ryzen 3 3200U - (8 GB/256 G...
3  HP MSO 2024 Intel Core i3 13th Gen 1315U - (16...
4  ASUS Chromebook CX15 Intel Celeron Dual Core N...

                                         Product_URL  Selling_Price  Platform
0  https://www.flipkart.com/asus-expertbook-p1-1-...         109990  Flipkart
1  https://www.flipkart.com/asus-expertbook-p1-1-...          99990  Flipkart
2  https://www.flipkart.com/acer-aspire-14-amd-ry...          79999  Flipkart
3  https://www.flipkart.com/hp-mso-2024-intel-cor...          67990  Flipkart
4  https://www.flipkart.com/asus-chromebook-cx15-...          24990  Flipkart

In [38]:
from sqlalchemy import create_engine
from getpass import getpass

password = getpass("Enter MySQL password: ")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/data_analysis"
)

print("MySQL connection created successfully!")

Enter MySQL password:  ········

MySQL connection created successfully!

In [39]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (1.2.3)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:
# Load 100 scraped products into MySQL

df.to_sql(
    name="price_monitoring_table",
    con=engine,
    if_exists="append",
    index=False
)

print("100 products loaded into MySQL successfully!")

100 products loaded into MySQL successfully!